### PR TITLE
code improvements

### PR DESCRIPTION
**Pull request by sosiska**
Some code improvements.

### CODE REVIEW

**Comment by sosiska** [comment]
Maybe replace
```go
if err = alpmHandle.SetSomeStuff(pacmanConf.SomeParam); err != nil {
		return err
}
```
to 
```go
if err = alpmHandle.SetSomeStuff(pacmanConf.SomeParam); err != nil {
		return err
}
```
and remove err declaration at the top of configureAlpm function?

**Comment by Morganamilo** [comment]
You're free to do that if you wish, would stop an assignment from being missed like that again.

**Comment by sosiska** [comment]
Done. I just wanted to avoid over allocating memory, but this is not a high load application. So now it looks prettier!
Should I squash commits or it's OK?

**Comment by Morganamilo** [comment]
Honestly I don't even know if it does allocate memory. And there's no need to squash them really. Merge commits and fixups I like to be squashed but small commits in general are fine.

**Pull request merged**
