### PR TITLE
Updates on PGP keys

### PR DESCRIPTION
**Pull request by qrwteyrutiyoup**
1 - Fix tests after #254 
2 - Add --gpg and --gpgflags alongside with respective entries in the manual and usage
3 - Update completion files for these flags

### CODE REVIEW

**Comment by Morganamilo** [comment]
Not home and on mobile so I cant do a full review, but one thing it looks like you need to add `gpgflags` to `hasparam()` in parser.go.

**Comment by qrwteyrutiyoup** [comment]
Oops, indeed, need to update hasParam, thanks.

**Comment by Morganamilo** [comment]
>One thing I've noticed is because we count missing keys as 'a non 0 return from gpg'. If the user sets --gpgflags to something invalid, it will count keys as invalid when really it's a gpg error.

>What's more annoying is that gpg seems to return the same error code for missing keys and invalid flags. I don't know of a way to handle this right now.

This still applies, it appears I made the comment on the commit and not the PR so it disappeared  when you rebased. It's not a big deal but something to point out.

I'm actually on a real PC this time and not mobile. So I have had a proper look. Thanks for the test fix, I forgot to check them. Everything else apart from the above point seems in order, I'll merge it now.

**Comment by qrwteyrutiyoup** [comment]
> This still applies, it appears I made the comment on the commit and not the PR so it disappeared when you rebased. It's not a big deal but something to point out.

Indeed, `gpg` does not make it easy to know what exactly failed, if the retrieving of keys itself or simply incorrect/ivalid parameters. 

How about adding something like "Please double check the extra arguments provided to gpg" to the error message, when `gpgflags` is set to something custom? Might at least give a better clue, in case of an error.

**Comment by Morganamilo** [comment]
I'm not a fan of warnings like that, if the user changes gpgflags I expect them to know what they're doing. Having to see a message every time just in case somebody does something wrong feels annoying and a little patronising.

Personally I would just mention it in the manpage where there's room for detailed information and the user is free to check at any time.

**Comment by Morganamilo** [comment]
Also thinking about it. The first `gpg` call will fail causing Yay to think it needs the key. But the second call where it imports the key is displayed to the user. So gpg should display a decent error message there and Yay will exit.

**Comment by qrwteyrutiyoup** [comment]
Maybe we could use something like `gpg <gpgflags> --list-keys` as we enter `checkPgpKeys` as some sort of sanity check, before doing the actual checking/importing of keys. If it fails in there, it would be likely due to bad flags. 

`gpg` actually returns a string like `gpg: invalid option "--foo"` in this case, so we could use that message in `yay`'s error message.

**Comment by Morganamilo** [comment]
A pre-check could work, although I still don't really think it's really needed.

Parsing the error output I would rather not do, there's a ton of things that can go wrong other than invalid args, we can't check for them all. Exit status' were made for this but sadly gpg only ever returns 0, 1 or 2.

**Comment by qrwteyrutiyoup** [comment]
Ok, so I won't do anything here for now; it looks good the way it is currently IMO:
```
./yay -S --gpgflags "--foo" cower
[...]
==> Import?  [Y/n] 
:: Importing keys with gpg...
gpg: invalid option "--foo"
==> Error: Problem importing keys
```

**Comment by Morganamilo** [comment]
I am right in assuming the fish completion is still not updated right?

**Comment by qrwteyrutiyoup** [comment]
Right. I thought I had done it as well, but just checked out and I updated bash and zsh only.

**Comment by Morganamilo** [comment]
I just assumed you didn't do it because you don't run fish. I don't run fish either so that's why I normally let @Jguer do it. Not that its that hard to copy and paste a line and change the flag name.

I don't mind if you do it or not, just wanted to make sure this doesn't get forgotten about.

**Comment by Jguer** [comment]
Sweet, I run `fish` full time so I can test it out. Anymore place missing completions/documentation entries before release?

**Comment by qrwteyrutiyoup** [comment]
Just spotted a rogue `/n’` in the beginning of the man page. Other than that and this completion, I am not aware of something else :)

**Comment by Morganamilo** [comment]
Strange, how did I manage that? Through sed maybe?

I'll change it back to `'\" t` then.

**Comment by Morganamilo** [comment]
Anyway apart from that. I think the only new stuff we have is: `--gpg` `-gpgflags` `--rebuild*` and `-Qu`. I think the only thing missing is `--rebuild*`.

**Pull request merged**
