### PR TITLE
Sync with go-alpm master

### PR DESCRIPTION
**Pull request by x1b6e6**

### CODE REVIEW

**Comment by Jguer** [comment]
@x1b6e6 linter seems to not like your commit

As well if you could rebase you'll get `pacman-git` tests

**Comment by x1b6e6** [comment]
> linter seems to not like your commit

Yes. This caused by renamed function (fixed in Jguer/go-alpm#47). My bad.

**Comment by x1b6e6** [comment]
@Jguer rebased. Test failing because library `Morganamilo/go-pacmanconf` returning incorrect conf. Maybe this caused by [removing `TotalDownload` option from pacman](https://git.archlinux.org/pacman.git/commit/?id=41f9c50abf08e71aa5fd03568934ab80abc7715c).

**Comment by Morganamilo** [comment]
go-pacmanconf uses pacman-conf behind the scenes. Because total download is removed from pacman-git, pacman-conf will not include it in the generated config even though go-pacmanconf has support for it.

My advice is to just have it set to false in your tests.

**Comment by Morganamilo** [comment]
> @Jguer rebased. Test failing because library `Morganamilo/go-pacmanconf` returning incorrect conf. Maybe this caused by [removing `TotalDownload` option from pacman](https://git.archlinux.org/pacman.git/commit/?id=41f9c50abf08e71aa5fd03568934ab80abc7715c).


Also I wonder who it was that made that commit hmmmmm....

**Comment by Jguer** [comment]
All good, let's merge this :+1:

**Pull request merged**
