### PR TITLE
add short option for --repo

### LINKED ISSUE #2082: Introduce short option for --repo
### Is your feature request related to a problem? Please describe.

Created from https://github.com/Jguer/yay/issues/2080

Introduce a short option for the existing long option `--repo`

### Describe the solution you'd like

`-n` as in `native` is the proposed short option but open to suggestions

### Describe alternatives you've considered

`-s` and `-r` and already in use by `--root` and `--search`

### PR DESCRIPTION
**Pull request by danieloh0714**
Add short option for the existing `--repo` option.

Decided to go with `-N` for "native" as `-n` is already [taken](https://github.com/Jguer/yay/blob/f7f2169992143d7e6d70fc32a4a2ea0d57fe730b/pkg/settings/parser/parser.go#L358). Open to changing, though.

Closes https://github.com/Jguer/yay/issues/2082

### CODE REVIEW

**Comment by danieloh0714** [comment]
@Jguer Is the [issue](https://github.com/Jguer/yay/issues/2082) this PR addresses still open?

**Comment by Jguer** [comment]
Hey Daniel, I don't have a better idea for the short option. I'm willing to give N a try. Would you mind updating the man page entry and the bash/fish completions?

**Comment by danieloh0714** [comment]
@Jguer I updated the man page and fish completion. I can't make sense of the bash completion file. I thought I would just look for the completion for the `-a, --aur` flag and replicate the logic, but I can't find that one.

**Comment by Jguer** [comment]
Thanks @danieloh0714 , I've added it (turns out a was missing, good call)

**Review by Jguer — APPROVED** [review]

**Comment by danieloh0714** [comment]
@Jguer Could we merge this PR?

**Comment by Jguer** [comment]
let's do it :+1:

**Pull request merged**
