### PR TITLE
Jguer/ /fix mflags

### PR DESCRIPTION
**Pull request by Jguer**

### CODE REVIEW

**Comment by grandchild** [comment]
```
❯ git checkout jguer/-/fix-mflags
❯ make
    [ ... ]
github.com/Jguer/yay/v10
❯ ./yay -S servefile --mflags=--nocheck
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  servefile-0.5.1-3

  1 servefile                        (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/1): servefile
  1 servefile                        (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
error resetting servefile: 
❯
```
(yes the part after the error was blank)

**Comment by grandchild** [comment]
If I `rm -rf ~/.cache/yay/servefile`, the error is similar:
```
❯ ./yay -S servefile --mflags=--nocheck
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  servefile-0.5.1-3

error cloning servefile: 
```

**Comment by Jguer** [comment]
> If I `rm -rf ~/.cache/yay/servefile`, the error is similar:
> 
> ```
> ❯ ./yay -S servefile --mflags=--nocheck
> :: Checking for conflicts...
> :: Checking for inner conflicts...
> [Aur:1]  servefile-0.5.1-3
> 
> error cloning servefile: 
> ```

Thanks for the test @grandchild , I believe now it should be good

**Comment by grandchild** [comment]
Yes, I can confirm that for `servefile` the tests are not run.

**Pull request merged**
