### PR TITLE
Improve printing

### LINKED ISSUE #128: light terminal background support
Hi there, the current colors are pretty hard to read in a light-on-dark terminal. An alternative color setting would be appreciated. Cheers.

### PR DESCRIPTION
**Pull request by Morganamilo**
Refactoring and general improvements to printing and specific improvements for light themes.
For more information see commits.

Before light:
image
After light:
image
Before dark:
image
After dark:
image

Do forgive the awful fonts. The pictures were takes with totally unconfigured terminals.

This should fix #128. Stuff like colours is highly opinion based, feedback would be great. Especially from @Jguer @ijanos @samosaara @heyitswither seems as you took intrest in the issue. I really dislike light themes myself so I would appreciate opinions from people who actually use them.

### CODE REVIEW

**Comment by Jguer** [comment]
I don't like light themes but when I give workshops and such they are the best to display on a projector so they have their use :laughing: . 

In regards to the colours, I like the yellow display of package names more than violet, but I need to check on my own colorscheme, probably doesn't look as dreadful as the tango theme but still we should strive to make it look good on the default colorscheme.

**Comment by Morganamilo** [comment]
Yellow looks pretty bad on light theme so I thought the easiest thing was just to full out replace it so I picked a colour that wasn't in use.

It does look a little bright though Maybe if I swap the colours on the package names and numbers so it's a slightly darker shade? Or swap maybe use the same colour that packages are in`-Ps`?

**Comment by Jguer** [comment]
What about package names cyan and version numbers purple, I haven't tested it

**Comment by Morganamilo** [comment]
Bold cyan looks pretty pad on white:
image

Non bold looks decent:
image

I think both work on dark:
image

image

**Comment by Jguer** [comment]
screenshot from 2018-03-02 13-03-00

screenshot from 2018-03-02 13-01-52

Actually looks decent on the first scheme. Maybe the non-bold blue will be better .I can already feel the complaints about the other theme being more familiar and better but for me it looks quite decent. 

An exception will need to be added to hash colour to not generate the same colour as package name otherwise it can be a bit hard on the eyes (check 6 community/kernel-headers-musl 3.12.6_5-1 (743.6 KiB 3.2 MiB) )

**Comment by Morganamilo** [comment]
Changed some more stuff. Went with cyan over blue for the packages because blue looks pretty bad on dark. I don;t think we need to a just `colour/hash()` because I'm using bold for the repo name and non bold for the package name.

Pushed the changes so you can test them.

**Comment by Jguer** [comment]
Yes, forgot I had bold turned off in my shell so I can't really tell the difference. But I like this last iteration. Let's say 1 day for any other input and merge?

**Comment by Jguer** [comment]
On an unrelated note, I would split into [votes] (popularity) or some easier way of reading it

**Comment by Morganamilo** [comment]
I grouped them together because they're very closely related. Same with download size and install size. But if you prefer we can come up with something else.

I still wanna look over this in a bit make sure it's consistent. All package names show up as cyan ect. I'm also considering refactoring away the colour functions for direct use.

Something like
```
func cyan(in string) string {
	if alpmConf.Options&alpm.ConfColor > 0 {
		return "\x1b[36m" + in + "\x1b[0m"
	}

	return in
}

packageColour := cyan
```

Then use packageColour() whenever printing package names. Could make it easier to change this stuff in the future. Probably won't implement this though at least for now. Just thinking about it.

**Comment by ijanos** [comment]
Hi there, so as a light theme user here is my opinion. 

The most important parts should always use the terminal foreground color, which is usually black or grey for the light theme users.  The most important things in the yay output are the package names so they should use the color I picked for the main foreground color in the terminal. This yellow on the screenshots are barely readable. 

I suggest looking at the pacaur color theme, I think they figured this thing out and it works just fine on a light terminal. See the attached an image:

pacaur

Thank you for asking for input and taking light color schemes into consideration.

**Comment by Morganamilo** [comment]
Alright so I got some decent fonts now so the screenshots don't look horrible.

As you suggested no colour just bold:
image

And here's cyan:
image

I do think the black is better there cause it stands out more.

same two for dark:
image

image

I do prefer the cyan here on the dark side but bold does work well here too so for the sake of compatibility it may be best to just do bold.

**Comment by Morganamilo** [comment]
Pushed some more changes. I encourage you to build this branch yourself if you're able @ijanos .

**Comment by ijanos** [comment]
Tried it, awesome work! 

yay

**Comment by Morganamilo** [comment]
looks like aur [installed] is set to green and bold while repo [instaled] is just green whoops. Need to fix that. Apart from that glad you like it, will probably finalise it here unless anyone else suggests some changes.

**Comment by ijanos** [comment]
Haha, I didnt even notice :) thank you again for this work.

**Comment by Morganamilo** [comment]
I say we merge this now then. I'm still open to feedback but we can deal with that in later PRs before release. Maybe the -git people will get an update and give us some feedback.

**Comment by Jguer** [comment]
I'm in for merging now

**Comment by Morganamilo** [comment]
Alright merged. This is was the last issue marked as a bug that I think is fixable this release.
#181 and #79 are basically the same thing and will be fixed with #166 
#146 I have ideas for but nothing concrete.

Once things settle and it seems there's no new critical bugs we should make a release. Then work on the last remaining bug issues. Both shouldn't be very hard but will require some sizeable changes to the code which is not what this release is about.

Also we need a vendor update too right?

**Comment by Jguer** [comment]
TODO:

- Vendor Update
- Update PKGBUILD with make
- Wait a bit for any waves
- Release

**Comment by Morganamilo** [comment]
Don't forget the -git package. Should go get yourself added as a co-maintainer.

**Comment by samosaara** [comment]
Um I'm not sure, but can we use the terminal's color pallete? Like 0 though 7 where 7th color is the bg and 1st is fg?

**Comment by Morganamilo** [comment]
We do use the terminal's colour pallet. The screenshots I've been sending have all been using the default colour schemes.

In reality with my theme Yay looks like this:
image

**Comment by Morganamilo** [comment]
@Jguer Also just remembered maybe update the screenshots on the readme?

**Pull request merged**
