### PR TITLE
Dependency system rewrite

### LINKED ISSUE #368: The dependencies of make depends aren't removed after installing packages
#### Affected Version
`yay v5.675`

#### Issue

If a make depend for an aur package has dependencies that also need to be installed, they aren't removed when answering `y` to `Remove make dependencies after install?`. As a result orphans will be left after the install.

But this is a small issue because it's a simple matter to run `yay -c` afterwards.

#### Steps to reproduce
Example package: [latte-dock-git](https://aur.archlinux.org/packages/latte-dock-git/)

The only make depends not already installed on my system are `cmake` and `extra-cmake-modules`. Their dependencies that aren't installed (recursive) are `libuv` and `rhash`.

1. `yay -S latte-dock-git`
2. `==> Remove make dependencies after install?  [y/N] y`

#### Expect:

```
[Repo Make: 4]  extra-cmake-modules-5.45.0-1 jsoncpp-1.8.4-2  libuv-1.20.1-1  rhash-1.3.6-1  cmake-3.10.3-1
[Aur: 2]  latte-dock-git-0.7.1.r573.g587d5786-1
```
After install all the two make depends and their dependencies are removed.

#### Actually get:
```
[Repo: 4]  jsoncpp-1.8.4-2  libuv-1.20.1-1  rhash-1.3.6-1  cmake-3.10.3-1
[Repo Make: 1]  extra-cmake-modules-5.45.0-1
[Aur: 2]  latte-dock-git-0.7.1.r573.g587d5786-1
```

After install only the make depend `extra-cmake-modules` is removed. 

I think `cmake` not being removed might be a separate but related issue: it seems if a make depend's dependencies includes another make depend (in this case `extra-cmake-modules` depends on `cmake`, but `cmake` is also a make depend) then that make depend (`cmake`) is not removed.

### LINKED ISSUE #422: Discrepancy between pacman upgrade and yay
#### Affected Version
yay v5.688

#### Issue
When I run yay -Syu I get:

```
:: 10 Packages to upgrade.
 10 core/curl                                             7.59.0-2 -> 7.60.0-1
  9 extra/libdrm                                          2.4.91-3 -> 2.4.92-1
  8 extra/mesa                                            18.0.3-3 -> 18.0.3-4
  7 extra/xf86-video-amdgpu                               18.0.1-1 -> 18.0.1-2
  6 extra/xorg-server                       1.19.6+13+gd0d1a694f-2 -> 1.20.0-2
  5 extra/xorg-server-common                1.19.6+13+gd0d1a694f-2 -> 1.20.0-2
  4 extra/xorg-server-xwayland              1.19.6+13+gd0d1a694f-2 -> 1.20.0-2
  3 community/libcurl-gnutls                              7.59.0-1 -> 7.60.0-1
  2 aur/jriver-media-center24                            24.0.24-2 -> 24.0.28-2
  1 aur/visual-studio-code-bin                            1.23.0-1 -> 1.23.1-1
==> Packages to not upgrade: (eg: 1 2 3, 1-3, ^4 or repo name)
==> Y

:: Checking for conflicts...
:: Checking for inner conflicts...

==> Package conflicts found:
 **-> Installing xf86-video-amdgpu will remove: xorg-server**
```
See the last line there?

```
$ sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 archzfs is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Package (8)                 Old Version             New Version  Net Change  Download Size

core/curl                   7.59.0-2                7.60.0-1      -0.07 MiB       0.89 MiB
community/libcurl-gnutls    7.59.0-1                7.60.0-1      -0.02 MiB       0.19 MiB
extra/libdrm                2.4.91-3                2.4.92-1       0.01 MiB       0.23 MiB
extra/mesa                  18.0.3-3                18.0.3-4       0.00 MiB      12.23 MiB
extra/xf86-video-amdgpu     18.0.1-1                18.0.1-2       0.05 MiB       0.06 MiB
extra/xorg-server           1.19.6+13+gd0d1a694f-2  1.20.0-2       2.16 MiB       1.25 MiB
extra/xorg-server-common    1.19.6+13+gd0d1a694f-2  1.20.0-2       0.05 MiB       0.03 MiB
extra/xorg-server-xwayland  1.19.6+13+gd0d1a694f-2  1.20.0-2      -0.05 MiB       0.76 MiB

Total Download Size:   15.64 MiB
Total Installed Size:  67.30 MiB
Net Upgrade Size:       2.14 MiB

:: Proceed with installation? [Y/n] 
```
This simply upgrades everything.

#### Steps to reproduce
$ yay -Syu
and
$ sudo pacman -Syu

Running yay after pacman -Syu works fine.

### PR DESCRIPTION
**Pull request by Morganamilo**
The current dependency system has gotten a bit bloated. After it was originally written versioned deps, db/name support and other little things were added on. This ended up with a lot oh hacked together code to work with the existing system and of course bugs.

This rewrite aims to be mostly the same, with a few improvements and much cleaner code. Currently it supports mostly everything that it did before.

### Improvements
Hopefully the cleaner code and more thought out version checking will fix stuff like https://github.com/Jguer/yay/issues/319#issuecomment-386725934

Fixes #368 

Slightly less over the top conflict messages

Better missing package text:
image

AUR provide solver #18: 
image

TODO:

- [x] Finish up some stuff in the code
- [ ] Comments
- [ ] Tests
- [ ] Decide on how the AUR warnings should work
- [ ] handle mixed aur and repo provides?
- [ ] Better handling of makedeps? #398 

Fixes #422 #416 #368 #18

### CODE REVIEW

**Comment by Morganamilo** [comment]
Also I'm obviously looking to merge this after the next release. After the news stuff is sorted out I'd like a new release.

**Comment by AladW** [comment]
How does the providers menu for AUR work? Clearly the information is not on the AUR RPC and I have no idea what to make of the client code used here.

**Comment by Morganamilo** [comment]
https://github.com/Morganamilo/yay/blob/deps3/depPool.go#L158-L170

**Comment by Morganamilo** [comment]
It's been an idea I've had for a while. I was doing this rewrite anyway and this ended up being pretty easy to add in and not too slow. If/when the rpc supports provides I can just delete that function and it should just work.

**Comment by AladW** [comment]
Thanks. Should work in most cases since it's unlikely a provider has no references to the provided package in either name or description.

**Comment by Jguer** [comment]
I'll review it as soon as I can. Of course, this will require a full release cycle almost in-vitro to troubleshoot

**Comment by Jguer** [comment]
Waiting on #396 and #386 to reach feature freeze (or even before if it's taking too long to get it proper). Some nice days of testing and then we enter a more interesting cycle

**Comment by Jguer** [comment]
I decided to test it with a package list after merging it (deletion of `dependencies.go` and change `warnings.Print to warnings.print`.

Package list
```
airgeddon-git
android-sdk-platform-tools
awmtt
bouml
browserpass
capitaine-cursors
cmus-git
cpplint
i3lock-color-git
js-beautify
light
neovim-symlinks
office-code-pro
pngout
python-gtts
shfmt
skypeforlinux-preview-bin
steam-fonts
stepmania-git
svox-pico-bin
torguard
ttf-iosevka-ss04
ttf-iosevka-term-ss04
ttf-ms-fonts
virtualbox-ext-oracle
wifijammer-git
yay
```

Output on master branch:
```
[Repo: 1]  perl-locale-gettext-1.07-5
[Repo Make: 1]  help2man-1.47.6-1
[Aur: 27]  stepmania-git-5.1.0a3+183+g500cfdfb62-1  svox-pico-bin-1.0+git20130326-5  torguard-0.3.84-1  virtualbox-ext-oracle-5.2.12-1  js-beautify-1.7.5-1  pngout-20150319-1  skypeforlinux-preview-bin-8.22.76.6-1  airgeddon-git-r1151.9cd1657-1  browserpass-2.0.21-1  capitaine-cursors-r2.1-1  light-1.0-2  shfmt-2.4.0-1  ttf-iosevka-term-ss04-1.14.3-1  i3lock-color-git-r483.e07c3f0-1  office-code-pro-1.004-2  steam-fonts-1.0.0-3  android-sdk-platform-tools-r27.0.1-1  awmtt-0.5-1  cpplint-456.r38-1  ttf-ms-fonts-2.0-10  yay-6.777-2  bouml-7.5-1  cmus-git-v2.7.0.r2.gc22b5bd-1  python-gtts-1.2.2-1  neovim-symlinks-3-1  ttf-iosevka-ss04-1.14.3-1  wifijammer-git-r72.5da3b2a-1
```

Output on `Morganamilo-deps3` (and it's slower, you'll see understandably why):
```
 -> Orphaned AUR Packages:  opencobolide  nodejs-generator-karma  meliaesvg-dark-icon-theme  nodejs-docco  nodejs-ionic  nginx-mainline-libressl  osec  ha-bridge  superbeam  lightdm-gtk-greeter-devel  mingw-w64-json-glib  nodejs-gitbook-cli  arora-git  xcursor-ardoise-translucent  ircd-hybrid  virtualbox-ck-host-modules  python2-json-rpc  okular-light  ttf-nishiki-teki  nodejs-tldr-git  qlipper  cpy  python2-p4a-build  python-js2py  clipit-gtk3  nodejs-gitbook  eggwm-qt5  xfmedia  asus-nb-wmi-reload-git  haskell-hssyck  virtualbox-luca020400-guest-modules  steamforwarder  ruby-url_safe_base64  python-pyjsparser  lightdm-gtk-greeter-bzr  virtualbox-ck-guest-modules  python-p4a-build  gpicview-gimp  python2-hyp  stepmania  nodejs-generator-mobileangularui  android-armv7a-eabi-system-image-23  sc-controller-git  nodejs-0.12  cocos2d-x-src  libreoffice-extension-coooder  nodejs-is-up  android-x86-system-image-22  python2-gcm  shadowsocks-libev-ipv6first  python2-jsonrpclib-git  nodejs-jake  ruby-babel-transpiler  android-docs  prosody-hg-stable  luvit  softmaker-office-2012-bin  soundpipe-dev  nwjs  gtkhtml3  ttf-fantasque-sans-git  kjs-git  nodejs-jsfmt  ttf-caracteres  ttf-kanjistrokeorders  heli-x6  libreoffice-extension-vero  frequest-git  nodejs-now  python-cligj  ewebkit-svn  ruby-babel-source  rst2html5  cmus-mediakeys  qtcreator36  vim-ferm  android-google-apis-23  matrix-js-sdk  python2-python-jsonrpc  nodejs-jsxhint  neovim-commentary  alduin  nginx-accesskey  python-tablib  android-studio-launcher  mingw-w64-sdl_ttf  ttf-sarasa-gothic-ttf  nodejs-latest-bin  fluxgui  nodejs-generator-angular  kjsembed-git  ttf-dosega  weborf  lightfirefox  python-efl-git  nodejs-react-tools  nodejs-winston  ttf-inconsolata-gwf  coolmaster-keyboard  wine-tim  python2-androguard  spectacle-light  mss-saliency-git  nodejs-markdown-live  python2-buildozer  lightmediascanner  haskell-curl-aeson  mingw-w64-yajl  safejumper  ttf-abibas  ttf-dejavu-snapshot  ruby-json-jwt  nodejs-pulp  geo-sans-light  nextcloud-app-onlyoffice-git  nodejs-gitignore  xorg-xbacklight-lxhillwind-patch  libxtract-git  jwt-go  lighttable-git  android-sources-22  nodejs-ws  libreoffice-fresh-rpm  python2-efl-git  nodejs-choo-cli  cairo-dock-git  tuprolog  ttf-press-start-2p  nodejs-jade  neovim-jellybeans  terminus-font-ll2-td1-ttf  nodejs-esformatter-jsx  qweborf  steambridge-git  android-armv7a-eabi-system-image-22  swagger-dsl  python2-pysolr  boblight  mingw-w64-jansson  electrum-dash  soundpipe-git  android-x86-64-system-image-23  stoplight-desktop-bin  virtualbox-luca020400-host-modules  lightdm-webkit-archsingle-theme-git  lighthouse-bitcoin  nodejs-generator-gulp-angular  neovim-remote-git  lwp  jstock  ttf-i.bming  nginx-tcp  parboiled  android-x86-64-system-image-24  maynard-git  ruby-tzinfo  ttf-inziu-iosevka-ttfs  bpkg-git  anttweakbar  ttf-trigger  conky-mt  ttf-animeace  ruby-json-1  ttf-invader  python2-palm  ompi  browserpass-bin  ruby-hiera-1  jslint  vim-mark  stoplight-bin  python2-tablib  python2-js2py  android-sources-24  bubbleupnpserver  python2-sanction  python2-pyjsparser  office-runner  zenbound2  python2-lasso  ttf-inziu-iosevka  nodejs-pass-server-node  vboxwrapper
 -> Out Of Date AUR Packages:  nodejs-node-forge  nodejs-docco  nodejs-ionic  nginx-mainline-libressl  ha-bridge  nodejs-nan  superbeam  nodejs-gitbook-cli  xcursor-ardoise-translucent  magicq  virtualbox-ck-host-modules  preflight-app  virtualbox-i3-host-dkms  cpuminer-multi  ttf-nishiki-teki  stepmania-theme-spawncamping-wallhack  qlipper  lib32-jsoncpp  nodejs-atob  clipit-gtk3  inspircd  clevo-wmi-dkms-git  jstest-gtk-git  nodejs-jsonlint  android-google-apis-x86-64  haskell-hssyck  nginx-custom-dev  steamforwarder  lifx-firmware-update  nodejs-hubot  virtualbox-ck-guest-modules  steamkit  gpicview-gimp  magicavoxel  torrentflix  nodejs-ajv  cocos2d-x-src  nodejs-is-up  perl-dancer2  mpd-light-pulse  nodejs-nodeunit  taskd-git  anyk  birdfont  hyperion-rpi-git  guile-json  python2-gcm  ttf-beteckna  python-httpie-jwt-auth  mupdf-nojs  libwebsockets15  riak  ttf-vista-fonts  python-nodeenv  gtksourceview3-git  xfce4-power-manager-xbacklight  ttf-emojione-color  demjson  python-apscheduler  sldr  mupdf-gl-nojs  lightdm-unity-greeter  nodejs-webpack  heli-x6  ttf-pragmatapro  pipelight  virtualbox-guest-modules-lts  nodejs-now  virtualbox-i3-guest-dkms  jsignpdf  lnd-git  nodejs-babel  betterlockscreen-git  virtualbox-i3-sdk  librepilot  android-x86-64-system-image  virtualbox-host-modules-mainline  nodejs-termcolors  mingw-w64-sdl_ttf  nodejs-latest-bin  ftl  ttf-pt-fonts  pilight-git  weborf  nodejs-winston  ttf-inconsolata-gwf  nodenv-node-build  python2-androguard  redex  kdeplasma-applets-steamcompanion  likwid  spectacle-light  candra-themes-3.20-1  nginx-oboe  virtualbox-i3-ext-vnc  nodejs-configurable-http-proxy  eigen3-hg  python-meteor-ejson  adbfs-rootless-git  lightdm-enso-os-greeter-git  nodejs-jshint  python2-nodeenv  virtualbox-host-modules-lts  sm5-simply-love  cysboard-git  virtualbox-i3  safejumper  nodejs-buster  vimprobable2-git  ttf-dejavu-snapshot  erlang-jsx  nodejs-pulp  android-support  nodejs-grunt  physlock-git  nodejs-gitignore  tuiview  nodejs-brunch  nodejs-async  libxtract-git  pegdown  featherpad  libejdb  nodejs-ws  python2-oletools  python-pyee  nodejs-how2  nodejs-generator-angular-fullstack  tuprolog  virtualbox-i3-guest-utils  python2-frida  ttf-twemoji-color  xed-bin  virtualbox-modules-pf  qweborf  nodejs-heroku-cli  ruby-json_pure  ttf-noto  nodejs-wstunnel  nodejs-marked  fgrun  mingw-w64-jansson  ewebkit  electrum-dash  heli-x  pktriggercord  android-studio-canary  moonlight  virtualbox-guest-modules-mainline  lightdm-webkit-archsingle-theme-git  notes-git  libjson-rpc-cpp  python-elementtree  nodejs-barcelona  python-lasagne-git  libreoffice-online  gog-torchlight2  mupdf-tools-nojs  virtualbox-bin  nginx-http-auth-digest  nginx-tcp  parboiled  nodejs-azure-cli  econnman  ttf-octicons  python2-androguard-git  i3lock-background  libmupdf-nojs  android-google-apis-armv7a-eabi  spoqa-han-sans  nodejs-addons-linter  gplaycli  python2-meteor-ejson  lightum-git  android-sources  browserpass-bin  opensesame  python2-genson  python2-suds-jurko  pgcli  haraka  confd  gog-hyper-light-drifter  ttf-fixedsys-excelsior-linux  nodejs-doctoc  virt-viewer-git  opentrack  pcmanfm-git  onlyoffice-desktopeditors-portable  e-modules-extra-git  eclipse-android  nodejs-ajv-cli  libreoffice-extension-ooolilypond
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo Make: 2]  perl-locale-gettext-1.07-5  help2man-1.47.6-1
[Aur: 27]  android-sdk-platform-tools-r27.0.1-1  i3lock-color-git-r483.e07c3f0-1  python-gtts-1.2.2-1  shfmt-2.4.0-1  ttf-iosevka-term-ss04-1.14.3-1  airgeddon-git-r1151.9cd1657-1  capitaine-cursors-r2.1-1  cpplint-456.r38-1  pngout-20150319-1  virtualbox-ext-oracle-5.2.12-1  yay-6.777-2  office-code-pro-1.004-2  ttf-ms-fonts-2.0-10  cmus-git-v2.7.0.r2.gc22b5bd-1  skypeforlinux-preview-bin-8.22.76.6-1  stepmania-git-5.1.0a3+183+g500cfdfb62-1  svox-pico-bin-1.0+git20130326-5  wifijammer-git-r72.5da3b2a-1  browserpass-2.0.21-1  js-beautify-1.7.5-1  neovim-symlinks-3-1  awmtt-0.5-1  bouml-7.5-1  torguard-0.3.84-1  ttf-iosevka-ss04-1.14.3-1  light-1.0-2  steam-fonts-1.0.0-3
```
If I have time today I'll dig into it today.

**Comment by Morganamilo** [comment]
Provider searching has been set to true by default, It does slow things down a bit but shouldn't be noticeable unless dealing with huge trees such as `ros-lunar-desktop-full`, even then it takes 5s rather than 2.5s.

**Comment by Morganamilo** [comment]
@Jguer This seems ready to merge. There's still a lot to be done, especially With documenting stuff. But for now it seems to work well and can finally go into master so I don't feel like I'm holding everyone up.

I suggest you play around with `yay -S foo` where foo is not already installed and there are other packages that provide foo.

I should also run this through a ros build. But I'll do that tomorrow.

**Comment by Jguer** [comment]
I like what I see, give me one or two days to read it over, see if we haven't lost anything and I'll pull it into master. 

Tell me how the ros-kinetic/ros-melodic build goes. When I'm done with writing the testing solution I'll be sure to include a ros like package

**Comment by Jguer** [comment]
Seems to be working fine. 
```
$ ./yay -S yay 
:: There are 3 providers available for yay:
:: Repository AUR
    1) yay 2) yay-bin 3) yay-git 

Enter a number (default=1): 
```
Niiice, although anti-interactivity folk is going to be pissed (on ahead because this already happens on pacman)

#### Unrelated whining
Here I'm just rambling with my biggest provides ~ass~ and my inability of finding a solution for this.
`jre` provides `java-runtime=10  java-runtime-headless=10  java-web-start=10  java-runtime-jre=10  java-runtime-headless-jre=10  java-web-start-jre=10  java-openjfx=10  jre10`
`jre10-openjdk` provides  ` java-runtime=10  java-runtime-openjdk=10`

```
./yay -S java-runtime                                                                                   0 < 14:48:54
:: There are 4 providers available for java-runtime:
:: Repository extra
    1) jre10-openjdk 2) jre7-openjdk 3) jre8-openjdk 4) jre9-openjdk 

Enter a number (default=1): 
```

`./yay -S jre10` will fail since the search is `jre10` which doesn't return `jre`

**Comment by Jguer** [comment]
> Yeah more splits could work, just need to be careful about the AUR not allowing search terms that are one char long.
I don't know if it was a typo but did you mean splitting more beyond the `-` or stripping the numbers from a package name? (I can think of `0ad` being a problem package in that regard, I guess a if len(pkgstrip) < 3, use pkg could fix that)

> Actually only returns repo results. If we find a package in the repos we don't bother to check the AUR. This could change though.

It's what we do in `yay -Si`, `yay` ... is always join the two, it wouldn't be an exception.

Haven't tested but will this work while sourcing dependencies?

**Comment by AladW** [comment]
I don't know if this is farfetched but maybe it would be useful to have a provides search for the intial query only (`--noprovides` would disable it for both the first `-S` command and when sourcing deps, right?)

**Comment by Jguer** [comment]
@Morganamilo I would just change what we discussed in the provides and merge it to master, continue debug and optimization/flag/documentation/refactoring from there, is that okay with you?

**Comment by Morganamilo** [comment]
And yes I'm happy to merge it now and keep working on it.

**Comment by Jguer** [comment]
Split `java-runtime` to `java` and `runtime` but strip `jre10` to `jre`

Okay, I'll merge it now, we may get some feedback from `yay-git` users if we broke something :angel:

**Comment by Morganamilo** [comment]
@AladW 

The provider prompt is pretty rare anyway. `you should get some prompts along the way.` was in reference to ros and you know how those are. I don't see a target only option getting much use.

**Pull request merged**
