### PR TITLE
Add bittin as translator

### PR DESCRIPTION
**Pull request by bittin**

### CODE REVIEW

**Comment by Jguer** [comment]
Hey @bittin , you already seem to be credited as the last translator on https://github.com/Jguer/yay/blob/16cce4384b13abebdbdb27707f698e785271c2fe/po/sv.po#L9

**Comment by Jguer** [comment]
(I can't seem to find how to add proper coauthoring to transifex PRs or attribution, if you know please tell)

**Comment by bittin** [comment]
@Jguer nope i don't updated the file with one extra line as i wanted to be added as a translator on Github, but if you don't wanna accept it and think being mentioned in the file is nice enough its all fine by me, also just updated to yay12 and works good :)

**Comment by Jguer** [comment]
If it matters to you, it matters to me, I'm merging it

**Review by Jguer — APPROVED** [review]

**Comment by bittin** [comment]
thanks :)

**Comment by bittin** [comment]
@Jguer Updated the Swedish on Transifex, however it failed the go linting step (feel like checking what i did wrong ? )

**Comment by bittin** [comment]
https://github.com/Jguer/yay/actions/runs/4603363182/jobs/8133299618 

seems a problem with the testing scripts in .go is the culprit not really a programmer myself however but would be good if you could check

**Pull request merged**
