### PR TITLE
Improved the cleaining operations.

### PR DESCRIPTION
**Pull request by roussak**
1. Appended the -n option to the cleanRemove and removeMake functions.
2. Make dependancies are installed with the --asdeps option.

### CODE REVIEW

**Comment by Jguer** [comment]
Sorry, first reason I haven't checked this PR is that the tests are failing.

```
install.go:369:8: Error return value of `asdeps` is not checked (errcheck)
	asdeps(parser, makeDeps.ToSlice())
	      ^
make: *** [Makefile:87: lint] Error 1
##[error]Process completed with exit code 2.
```
Once this is fixed I'll take a complete look at the PR

**Comment by roussak** [comment]
Thank you.I saw this error. But I am not sure where and how should I put the test(s).17 янв. 2020 г. 22:35 пользователь J Guerreiro <notifications@github.com> написал:Sorry, first reason I haven't checked this PR is that the tests are failing.
install.go:369:8: Error return value of `asdeps` is not checked (errcheck)
	asdeps(parser, makeDeps.ToSlice())
	      ^
make: *** [Makefile:87: lint] Error 1
##[error]Process completed with exit code 2.

Once this is fixed I'll take a complete look at the PR

**Comment by Morganamilo** [comment]
I am for sure against adding `--nosave` to your remove options.

**Comment by roussak** [comment]
But this is not a "simple" remove -- it's the cleanRemove.

**Pull request closed without merging**
