### PR TITLE
Update email

### PR DESCRIPTION
**Pull request by Morganamilo**

### CODE REVIEW

**Comment by Morganamilo** [comment]
By the way, would be nice to get my collaborator back :)

**Comment by Morganamilo** [comment]
@Jguer Bump?

**Comment by Jguer** [comment]
Sure thing, sorry for the delay, I've added a small section on other AUR helpers/tools by the way, any other worthwhile addition?

**Comment by Morganamilo** [comment]
Well you've seen my point on paru. :P 

Although it should be lower case p for consistency.

However you may as well just link the aur helpers wiki page imo.

**Comment by Morganamilo** [comment]
Is there any reason this was not merged?

**Comment by Jguer** [comment]
@Morganamilo I thought I had rebased it with mine when actually I didn't. Fixed.

**Pull request merged**
