### PR TITLE
Support Usage in pacman.conf

### PR DESCRIPTION
**Pull request by Morganamilo**
This also increases out reliance on alpm. The code is now faster, more correct and there is less of it. (Although you can argue there's more code on the go-alpm side)

Depends on https://github.com/Jguer/go-alpm/pull/17

### CODE REVIEW

**Comment by Jguer** [comment]
I'm okay with moving stuff to `go-alpm`, seems cleaner code anyway

**Comment by Morganamilo** [comment]
Reading over this again in the morning, I've realized a typo or two and I think this stops the "ignoreing upgrade" mesage for repo upgrades. But that can probably be fixed by letting the logcb or however pacman prints them.

**Comment by Morganamilo** [comment]
Sadly we can not control the output of alpm's warnings. So it looks a little out of place.

image

We could restructure out warnings to be  `pkgname: text (version1 => version2)` and it would be close, we would lose the colour though which is kind of annoying.

**Comment by Jguer** [comment]
That is kind of problematic, We could keep the colour and still change to `=>` anyway and change to example: -> linux-ck: ignoring package upgrade  (version1 => version2) with the colour

**Pull request merged**
