### PR TITLE
 Use numbermenu for cleanBuilds and editPkgbuilds

### PR DESCRIPTION
**Pull request by Morganamilo**
Finally got around to implementing the numbermenu you suggested in #109 along with some refactoring of the numbermenu system. I'm going to keep this brief and not going to explain how the number menu works in hopes that you try it out and can give it a blind test.

I expect the usual back and forth of formatting changes before merging, feedback welcome.

### CODE REVIEW

**Comment by Jguer** [comment]
I'll check it today no worries

**Comment by Jguer** [comment]
Was working fine, I've merged, will try to fix some alignment though

**Comment by Morganamilo** [comment]
You wanted to make a new release so I was holding out on that before merging. Seems as you merged this I'll merge my other PR and give the release a little more time so we got a chance to test.

**Comment by Jguer** [comment]
I merged it because it's a display issue. The problems will appear fast.
The goroutines pull request if it's bugged will only show issues later on

**Comment by Morganamilo** [comment]
Is that a no for merge then? I'll wait for the next release then.

This PR does quite a lot logic wise though so more that display issues are possible.

**Comment by Jguer** [comment]
From what I tested it seemed well, it survived a `yay -S (yay -Qeq`)

**Comment by Jguer** [comment]
If you think the goroutine pull is lower risk, feel free to pull it. I'm updating fish completions now and I'll finish bash completions as well.

**Comment by Morganamilo** [comment]
Nah I'll just wait, safer anyway. I'll start the Zsh stuff then.

**Pull request merged**
