### PR TITLE
WIP: Atomic refactoring into modules.

### PR DESCRIPTION
**Pull request by Jguer**
As development has stalled on most fronts and branches have gone stale, this seems like the best time to try and pass to modules (#759). Due to the interdependencies in the code an incremental approach was not as feasible. 

Care was taken not to change application/operational logic and to keep user behaviour exactly the same (even though some points will require this). The main objective is the removal of global variables for ease of testing specially.

It is grossly over packaged but should allow interface logic to be gradually split from core.

TODO:
- Fix callbacks. Current method will definitely break in case of config pointer change or release of handle.
- Fix unit tests and start adding unit tests, starting at lv3 deep packages and moving to interface.
- Add Integration tests using containers
- Document exports

- Remove smallArrow and arrow (they were left as a nag to continue refactoring)
- Coloring should be done in `text`, functions should call predefined methods such as Info, Warning, Error, List... (TODO in TODO: find morganamilo's text on required steps for localisation) 

To review:
- `main.go` was kept in the main directory for compatibility purposes. `pkg/cmd/yay` would be the natural place to put it.
- creation of internal packages for functions that handle mostly interface options.

### CODE REVIEW

**Comment by Jguer** [comment]
yay-new

Yay-next main package separation displayed up

Yay master branch without package separation (as there is only one package)
yay-old

**Comment by Morganamilo** [comment]
My intention was to do this one module at a time? Doing this all at once seem like a huge task.

**Comment by Jguer** [comment]
Unglobalization of parameters didn't seem as something as doable as just atomically breaking it up into modules. Runtime for example can still have more modules extracted or collapsed into it. 

As application logic didn't change* it was mostly a refactoring job.

*The only change that broke application logic was removing config.noConfirm and HideMenus overrides from various functions and passing them on directly to the functions. Just the callback code for alpm is giving some headaches with this change as I was not as comfortable with it as I thought

**Comment by Jguer** [comment]
*Although as they are now, modules such as types or completion should be easy to integrate in master. Anything that touches config or the main globals tends to break in a way or two

**Comment by Jguer** [comment]
This branch is not going to be merged and remains only as a possible discussion/preview branch.

**Pull request closed without merging**
