### PR TITLE
Print errors on stderr

### PR DESCRIPTION
**Pull request by frebib**
This makes a start on fixing https://github.com/Jguer/yay/issues/715
It is by no means a complete solution, but instead a start.

This only touches all actual errors, not interactive prompt errors or anything like that.
I feel like those are a stylistic choice and should be discussed before anything happens with them.

### CODE REVIEW

**Comment by Morganamilo** [comment]
I've had a plan in place for some time, I'm not sure if I've ever spelt it out exactly.

1. Merge new config system or rather $current_big_change
2. Convert all prints from +'ing strings to printf formatting
3. Erase '::' arrow, smallArror. error, etc for wrapper functions `errPrintf` `infoPrintf`, etc
4. Add in localisation 

Each step is gated behind the next, everything needs to be in printf format for localisation to work, I don't want to start localisation work until $current_big_change is finished and so on.

So ideally in my plan stderr printing would come in step 3 via errPrintf or whatever.

But right now I'm busy and have hardly been doing anything related to yay, so I think it would be unfair to gate PRs on stuff that probably wont get done for months. Plus I don't mind resolving conflicts.

So consider this merged after I actually check through it. And if you feel like doing any of the other points feel free.

**Comment by Morganamilo** [comment]
>Do you need any help on that?
I don't really need help, I've just been slacking. I can upload the code if you want to continue working on it.

**Comment by Morganamilo** [comment]
@frebib looks like this PR misses quite a bit of printlns. callbacks.go:70 download.go:168,172 and so on. Github's review system doesn't really let me comment on thing you didn't change so I'll let you figure it out. ;)

I'm not sure how were searching for things to change but I would recommend something along the lines of `grep -rn Println`.

**Comment by frebib** [comment]
Yeah there were some I wasn't sure about. I wasn't sure what to classify as an "error" as such or just standard output.
Would you classify errors caused by user input worthy of stderr? I'm happy to make changes to suit but it would be useful to have a baseline to work from

**Comment by Morganamilo** [comment]
If the variable's name is err or is prefixed with red(arrow) it should probably be printed to stderr.

Stuff like "Input too long" should go on stderr.

I'm tempted to put all of the warnings on stderr too as this is what pacman does. But deciding what is info and what is a warning is annoying and difficult so leave it.

**Comment by frebib** [comment]
I should ask now, would you rather warnings be printed on stdout or stderr?

**Comment by Morganamilo** [comment]
By leave it I meant don't bother with the warnings (for now at least).

**Comment by frebib** [comment]
Apologies, I didn't read your previous comment. You did obviously say to leave the warnings, I'm just blind.

I've amended my commit making sure to get anything with `red(..)` output and also empty newlines that are related to error output.
Let me know how this looks and if I can make any improvements

**Comment by Morganamilo** [comment]
Looks goo to me, can't see anything missed out.

**Pull request merged**
