### PR TITLE
Print warnings about newer local packages then remote versions

### PR DESCRIPTION
**Pull request by AlexWayfer**
Inspired by [`pakku`](https://github.com/kitsunyan/pakku)

Before:

image

After:

image

(I'm not sure about format, colors and condition, but this info is very helpful).

### CODE REVIEW

**Comment by Morganamilo** [comment]
You should probably use smallArrow over the warning text, Also it's worth noting -git packages always appear newer than the version in the AUR, and It's quite annoying:
image

**Comment by AlexWayfer** [comment]
OK. I'll test and change it on the computer with non-git packages (on my current there are only git packages). Tomorrow, I guess.

**Comment by AlexWayfer** [comment]
> Also it's worth noting -git packages always appear newer than the version in the AUR, and It's quite annoying

How can I check this? Just by name suffix?

**Comment by Morganamilo** [comment]
That's all you can do really. See `isDevelName()`.

**Comment by AlexWayfer** [comment]
> See isDevelName().

Thank you. I think I should ignore packages with all these suffixes from this function: `svn`, `nightly`, etc.

**Comment by AlexWayfer** [comment]
> You should probably use smallArrow over the warning text

Used (yellow and bold).

> `isDevelName()`

Used.

**Comment by Morganamilo** [comment]
The pkgname should be coloured the same as the ignore upgrade text. Also now we have a mix of messaged that start with text then say the package name and we have some messages that do the opposite. One of them should be swapped around.

**Comment by AlexWayfer** [comment]
> I think color of "Out Of Date AUR Packages" is better.

Made:
image

**Comment by Morganamilo** [comment]
>I think color of "Out Of Date AUR Packages" is better.

They're both the same colour.

**Comment by AlexWayfer** [comment]
> They're both the same colour.

Nope: `cyan` in "Out of date" and `magenta` in number of upgrade.

Oh, sorry, I misread "ignore upgrade text".

OK, I'll try to do this.

(I can't figure out how to ignore multiple packages).

**Comment by Morganamilo** [comment]
```
--ignore <package>
           Directs pacman to ignore upgrades of package even if there is one available. Multiple
           packages can be specified by separating them with a comma.
```

**Comment by AlexWayfer** [comment]
Thank you. Early I got:

```
./yay -S --help

...

--ignore <pkg>   ignore a package upgrade (can be used more than once)
```

I thought the option can be used more than once. :man_shrugging: 

Separation with space didn't work.

**Comment by Morganamilo** [comment]
Funnily enough `--cachedir` can be used more than once, just like how you were trying to use ignore. Why? I have no idea?

>--ignore <pkg>   ignore a package upgrade (can be used more than once)

This does seem misleading. The message comes from Pacman though, maybe check if there's already something open about it?

**Comment by Morganamilo** [comment]
>Should I make this messages in separate cycle, or mix messages about ignoring and local newer is fine?

I don't really mind really, you could have it do newer warnings then ignore warnings but still in the same block. But that would probably require some refactoring.

**Comment by AlexWayfer** [comment]
> What I mean is. The ignore package text starts with some text then says the package name. While the local is newer starts with the package name then has some text. Its inconsistent and one should be swapped.

Done. I also changed `=>` to `->` in ignore packages, how it's in local newer packages and upgrade packages.

> The message comes from Pacman though

Yeah, that's true.

> maybe check if there's already something open about it?

I didn't found.

> I don't really mind really, you could have it do newer warnings then ignore warnings but still in the same block. But that would probably require some refactoring.

OK, I'll try. For now it looks like this:

image

**Comment by AlexWayfer** [comment]
> I don't really mind really, you could have it do newer warnings then ignore warnings but still in the same block. But that would probably require some refactoring.

I think it's done now:

image

**Comment by AlexWayfer** [comment]
(Probably, we can print this lists as upgrade table, but I'm not sure that this is good idea)

**Comment by Morganamilo** [comment]
>Done. I also changed => to -> in ignore packages, how it's in local newer packages and upgrade packages.

Funny thing is I changed it from `->` to `=>` because `=>` is what Pacman uses. We do use `->` in the menu and honestly I find `->` to look better anyway so I don't mind changing it back.

I'm happy with how it is now though (apart from the syntax errorr ;)).

**Comment by AlexWayfer** [comment]
> because => is what Pacman uses

Where?!

> We do use -> in the menu and honestly I find -> to look better anyway so I don't mind changing it back.

OK… I can type any thing. I just want to see the same thing between sections.

> apart from the syntax errorr ;)

Oh… Sorry. I still not used to Go, and plugin with `gofmt` doesn't work in this case.

**Comment by Morganamilo** [comment]
>Where?!

Here:
image

**Comment by Morganamilo** [comment]
image


Looks like you didn't change all of the `->`. Whatever you pick make sure to change them all. Maybe extract them all into a function.

**Comment by AlexWayfer** [comment]
> Here:

There is another format at all (`warning:`).

> Looks like you didn't change all of the ->. Whatever you pick make sure to change them all. Maybe extract them all into a function.

Thank you. Changed.

But I got mix of "repo ignored", "newer aur", "aur ignored":

image

:disappointed: 

I wanted to take off printing "newer" before "repo ignored", but these parts of code in `go` (routines?) and I'm stuck.

---

Oh, I can print this after all. Made this:

image

I think it's better than before.

**Comment by AlexWayfer** [comment]
> There is another format at all (warning:).

Oh. Or we can change format from `-> Text: package (versions)` to `warning: package: text (versions)` in both blocks (about ignoring and local newer), and make this as in `pacman`.

As you wish.

**Comment by Morganamilo** [comment]
Nah, I like the arrow format more than warning text.

When it comes to `-> package: text (versions)` vs `-> text: package (versions)` I did say above that I don't mind, as long as it's all consistent.

**Comment by Morganamilo** [comment]
You still haven't pushed the changes of the last image.

**Comment by AlexWayfer** [comment]
> You still haven't pushed the changes of the last image.

Are you sure?

I moved print-function call to the end of AUR qurery: https://github.com/Jguer/yay/pull/396/files#diff-135dc004c4305f5b7fe8d80752bd129aR271

**Comment by Morganamilo** [comment]
I haven't read the code yet so I don't know how it works but but this is what I'm getting:
image

**Comment by Morganamilo** [comment]
I looked at your code. Basically you only wait for the AUR update checks to finish, you forgot about the devel stuff.

Try this:
```patch
From 047dea3421b4bdd6b7918a05b31dc80d850ce1f8 Mon Sep 17 00:00:00 2001
From: morganamilo <morganamilo@gmail.com>
Date: Fri, 11 May 2018 21:02:36 +0100
Subject: [PATCH] Print local newer than text after ignore text

Signed-off-by: morganamilo <morganamilo@gmail.com>
---
 upgrade.go | 15 ++++++++-------
 1 file changed, 8 insertions(+), 7 deletions(-)

diff --git a/upgrade.go b/upgrade.go
index 6b6f445..c1555b4 100644
--- a/upgrade.go
+++ b/upgrade.go
@@ -138,6 +138,8 @@ func upList(warnings *aurWarnings) (aurUp upSlice, repoUp upSlice, err error) {
 	var aurErr error
 	var develErr error
 
+	var pkgdata = make(map[string]*rpc.Pkg)
+
 	fmt.Println(bold(cyan("::") + bold(" Searching databases for updates...")))
 	wg.Add(1)
 	go func() {
@@ -148,7 +150,7 @@ func upList(warnings *aurWarnings) (aurUp upSlice, repoUp upSlice, err error) {
 	fmt.Println(bold(cyan("::") + bold(" Searching AUR for updates...")))
 	wg.Add(1)
 	go func() {
-		aurUp, aurErr = upAUR(remote, remoteNames, warnings)
+		aurUp, aurErr = upAUR(remote, remoteNames, pkgdata, warnings)
 		wg.Done()
 	}()
 
@@ -163,6 +165,8 @@ func upList(warnings *aurWarnings) (aurUp upSlice, repoUp upSlice, err error) {
 
 	wg.Wait()
 
+	printLocalNewerThanAUR(remote, pkgdata)
+
 	errs := make([]string, 0)
 	for _, e := range []error{repoErr, aurErr, develErr} {
 		if e != nil {
@@ -240,15 +244,14 @@ func upDevel(remote []alpm.Package) (toUpgrade upSlice, err error) {
 
 // upAUR gathers foreign packages and checks if they have new versions.
 // Output: Upgrade type package list.
-func upAUR(remote []alpm.Package, remoteNames []string, warnings *aurWarnings) (upSlice, error) {
+func upAUR(remote []alpm.Package, remoteNames []string, pkgdata map[string]*rpc.Pkg, warnings *aurWarnings) (upSlice, error) {
 	toUpgrade := make(upSlice, 0)
-	_pkgdata, err := aurInfo(remoteNames, warnings)
+	info, err := aurInfo(remoteNames, warnings)
 	if err != nil {
 		return nil, err
 	}
 
-	pkgdata := make(map[string]*rpc.Pkg)
-	for _, pkg := range _pkgdata {
+	for _, pkg := range info {
 		pkgdata[pkg.Name] = pkg
 	}
 
@@ -268,8 +271,6 @@ func upAUR(remote []alpm.Package, remoteNames []string, warnings *aurWarnings) (
 		}
 	}
 
-	printLocalNewerThanAUR(remote, pkgdata)
-
 	return toUpgrade, nil
 }
 
-- 
2.17.0
```

**Comment by AlexWayfer** [comment]
> Basically you only wait for the AUR update checks to finish, you forgot about the devel stuff.

That's true — I don't have installed devel stuff.

> Try this:

Thank you, made like this.

**Comment by Jguer** [comment]
One down,  just another and I think we can call this stable.

**Pull request merged**
