### PR TITLE
Refactor part of UserExcludeUpgrades()

### PR DESCRIPTION
**Pull request by iTrooz**
Hey !

I was looking at UserExcludeUpgrades() for another PR, and had great difficulty to understand its code. So I ended up refactoring the function in order to understand it better.

Maybe there was a reason the function was written like that, or I was just not smart enough to understand, but since I've done it, I'm offering this refactor here in case it interests you.

### CODE REVIEW

**Comment by Jguer** [comment]
Hey @iTrooz , linting is failing on the PR, can you fix it up?

**Comment by iTrooz** [comment]
Done !

**Review by Jguer — APPROVED** [review]

**Comment by iTrooz** [comment]
Hey @Jguer any plans to merge ?

**Comment by Jguer** [comment]
Yes, let's do it :+1:

**Pull request merged**
