### PR TITLE
Add --mitmsslcert option

### PR DESCRIPTION
**Pull request by grandchild**
This is a draft for implementing a fix for jguer/yay#137 and jguer/yay#1386 ...

Two remarks:

* I'd appreciate feedback on code style and location. (Not sure where everything is supposed to go, this option should take effect pretty early in the code, so it's not buried very much, but maybe it's too central?)
* I have not tested this yet, I will probably do that on the weekend, using this approach: https://docs.mitmproxy.org/stable/howto-transparent-vms/ to simulate a corporate network HTTPS MITM.

### CODE REVIEW

**Comment by grandchild** [comment]
Translations are obviously missing as well, but that's for later.

**Comment by grandchild** [comment]
The name of the flag is also very much up for discussion.

**Comment by Jguer** [comment]
@grandchild I can review it and I can even accept it but how will you make sure that `PKGBUILDs` will actually download https content if the cert is only in store for `yay`? 

As far as I see this fix moves the issues to 2 separate points:
- File downloading in makepkg
- Database refresh on pacman

**Comment by Sohimaster** [comment]
@grandchild why should I provide sslCert file? Can I just disable mimt security check?

**Comment by Sohimaster** [comment]
@grandchild @Jguer for example in Postman I have option SSL certificate verification (on/off)

**Comment by grandchild** [comment]
@Sohimaster yes, you and @Jguer are both right, it doesn't make much sense this way.

It should be a mix of both "disable SSL verification" and editing `/etc/makepkg.conf` to add the necessary `curl` or `wget` options to `DLAGENTS`... I might look into this next week -- this week I probably won't have time anymore.

**Pull request closed without merging**
