### PR TITLE
Updated Basque translation

### PR DESCRIPTION
**Pull request by Porrumentzio**

### CODE REVIEW

**Comment by Jguer** [comment]
@r3v1 would you like to contest this translation?

**Review by r3v1 — APPROVED** [review]

**Comment by r3v1** [comment]
Mitico @Porrumentzio puta casualidad, banekien zu ezagutzen nuela ta ez nekien linux fan bat zinela, ondo ondo

**Comment by Porrumentzio** [comment]
@r3v1, zein zea? Ta zertaz ezautzeiazu?? :)

**Comment by r3v1** [comment]
Duela bi urte @Porrumentzio , EZAn, aka sofacama ;)

**Pull request merged**
