### PR TITLE
fix(installer): Fixes the same pkgbase being built multiple times

### LINKED ISSUE #2340: avoid multiple executions of makepkg for the same PKGBUILD
### Is your feature request related to a problem? Please describe.

I wanted to install some themes for GRUB, so I tried installing packages in [grub-themes-git](https://aur.archlinux.org/pkgbase/grub-themes-git) from AUR.

```bash
$ yay -S `cat grub-themes-git-package-list`
```

However, this command seems to do like this for the 57 package (I translated from Japanese so there may be different from the original version):

```
==> Making package: grub-themes-git 2022.10.30.r35.g000171d-1 (09/01/2024 01:03:04)
==> Checking the runtime's dependencies...
==> Checking the dependencies in the building time...
==> Retrieving the source...
  -> Syncing grub2-themes git repo...
==> Validating sources file with sha256sums...
    grub2-themes ... skipped
==> Deleting the existing $srcdir/ directory...
==> Expanding the source...
  -> Copying grub2-themes git for building...
Cloning into 'grub2-themes'...
done.
==> Starting pkgver()...
==> Prepared the source
 -> grub-themes-git-2022.10.30.r35.g000171d-1 has already existed -- Skipping to build
```

Each process took a lot, and the sum reached hours on my machine.

### Describe the solution you'd like

I think that yay command should skip preparing and building process for the packages whose PKGBUILD has been executed (in the same yay command's execution). In other words, I think that one PKGBUILD should be executed just once in single yay command's execution.

And also it may be a radical solution to implement the functionality for installing by pkgbase.

### PR DESCRIPTION
**Pull request by Ferdi265**
When building a PKGBUILD pkgbase with multiple pkgnames, `installAURPackages()` invokes `buildPkg()` multiple times for the same pkgbase. This causes `prepare()` to be run multiple times for the same pkgbase, since detection of already built packages happens after `prepare()`.

Additionally, detection of already built packages can fail if the split debug packages are enabled and the package does not contain any binaries, causing no `-debug` package to be created by makepkg even though it is listed by `makepkg --packagelist`.

This PR fixes this by keeping track of the pkgdests built by `buildPkg()` and avoiding rebuilds of the same pkgbase in the same yay invocation.

Fixes #2340.

### CODE REVIEW

**Comment by Ferdi265** [comment]
Just noticed this still has test failures locally, will fix those.

It appears I broke something related to installing built packages, marking this as a draft until that is fixed.

<details>
<summary>Broken tests as of d2837e1:</summary>

```
--- FAIL: TestIntegrationLocalInstall (0.00s)
--- FAIL: TestIntegrationLocalInstallNeeded (0.00s)
--- FAIL: TestIntegrationLocalInstallGenerateSRCINFO (0.00s)
--- FAIL: TestIntegrationLocalInstallWithDepsProvides (0.00s)
--- FAIL: TestIntegrationLocalInstallTwoSrcInfosWithDeps (0.00s)
--- FAIL: TestSyncUpgradeAURPinnedSplitPackage (0.01s)
--- FAIL: TestInstaller_KeepSrc (0.00s)
    --- FAIL: TestInstaller_KeepSrc/--keepsrc (0.00s)
--- FAIL: TestInstaller_InstallNeeded (0.01s)
    --- FAIL: TestInstaller_InstallNeeded/not_installed_and_not_built (0.00s)
    --- FAIL: TestInstaller_InstallNeeded/not_installed_and_built (0.00s)
--- FAIL: TestInstaller_InstallSplitPackage (0.01s)
    --- FAIL: TestInstaller_InstallSplitPackage/jellyfin (0.01s)
--- FAIL: TestInstaller_InstallRebuild (0.01s)
    --- FAIL: TestInstaller_InstallRebuild/--norebuild(default)_when_built_and_not_installed (0.00s)
    --- FAIL: TestInstaller_InstallRebuild/--rebuild_when_built_and_not_installed (0.00s)
    --- FAIL: TestInstaller_InstallRebuild/--rebuild_when_built_and_installed (0.00s)
    --- FAIL: TestInstaller_InstallRebuild/--rebuild_when_built_and_installed_previously_as_dep (0.00s)
--- FAIL: TestInstaller_CompileFailed (0.01s)
    --- FAIL: TestInstaller_CompileFailed/one_layer_--_fail_install (0.00s)
--- FAIL: TestInstaller_InstallMixedSourcesAndLayers (0.01s)
    --- FAIL: TestInstaller_InstallMixedSourcesAndLayers/same_layer_--_different_sources (0.00s)
    --- FAIL: TestInstaller_InstallMixedSourcesAndLayers/different_layer_--_different_sources (0.00s)
    --- FAIL: TestInstaller_InstallMixedSourcesAndLayers/same_layer_--_aur (0.00s)
    --- FAIL: TestInstaller_InstallMixedSourcesAndLayers/different_layer_--_aur (0.00s)
```
</details>

**Comment by Ferdi265** [comment]
Fixed accidently shadowing the `pkgdests` variable in d9e17f9. This caused installing built packages to be broken, which is now fixed.

<details>
<summary>Broken tests as of d9e17f9:</summary>

```
--- FAIL: TestIntegrationLocalInstall (0.00s)
--- FAIL: TestIntegrationLocalInstallNeeded (0.00s)
--- FAIL: TestIntegrationLocalInstallGenerateSRCINFO (0.00s)
--- FAIL: TestSyncUpgradeAURPinnedSplitPackage (0.01s)
--- FAIL: TestInstaller_InstallSplitPackage (0.00s)
    --- FAIL: TestInstaller_InstallSplitPackage/jellyfin (0.00s)
```
</details>

**Comment by Ferdi265** [comment]
The test changes in 5064027 only update the list of expected commands for building split packages, since some redundant invocations of `makepkg` have been removed by the changes in this PR.

Broken tests as of 5064027: all green :+1:

**Comment by Ferdi265** [comment]
Fixed another issue in a26822f: Previously, whether a pkgbase was built was considered part of `installer.origTargets` was dependent on the order of the packages. This wasn't as big of an issue before this PR since at least one of the `buildPkg()` invocations passed the correct value of `isTarget` to `buildPkg()`. d9e17f9 changed this to only a single invocation of `buildPkg()` per pkgbase, so now the `isTarget` argument has to be correct for the first (and only) invocation. Fixed this by tracking which pkgbases are part of `installer.origTargets` in `handleLayer()` and passing that to `installAURPackages()`.

**Review by Jguer — APPROVED** [review]
Looking good @Ferdi265 , let me play with it a bit locally to see if I can find a weird package that we currently support, otherwise all good to merge

**Comment by Jguer** [comment]
:+1: let's get some feedback from yay-git

**Pull request merged**
