### PR TITLE
Updated Readme to include note about dependencies

### PR DESCRIPTION
**Pull request by AdamGEmerson**
Per issue #1142 I've added a note to the readme to let users know they'll need to install `base-devel`.

### CODE REVIEW

**Comment by grandchild** [comment]
I would write plainly "Make sure you have the `base-devel` package group installed" -- since it's not just people who "have an issue with makepkg", everyone must have it installed.

People might overlook it initially, because... well, they don't have a problem with makepkg... yet. ;)

**Comment by AdamGEmerson** [comment]
I have updated the readme per @grandchild notes.

Let me know if you think there should be any addtional formatting tweaks.

**Comment by Jguer** [comment]
Thanks for your contribution, it is true that this should have been fixed a long time ago :sweat_smile:

**Comment by AdamGEmerson** [comment]
> Thanks for your contribution, it is true that this should have been fixed a long time ago 😅

No problem!  I'm just getting started trying to contribute on GitHub.  I'll keep a look out for issues I can tackle.

**Pull request merged**
