### PR TITLE
FR #994: Implement proper diff display

### PR DESCRIPTION
**Pull request by reyreaud-l**
As raised in #994, diff display was not proper when interrupting during
download or diff review.

This commit introduce:
- Add a ref in the git tree named "YAY_DIFF_REVIEW" which is set to the last
diff reviewed by the user.
- Change the function displaying diff to user to make proper use of this
new ref. If the ref does not exist in the git tree, it will display the
diff from origin to HEAD@{upstream}.
- Add a function updating the YAY_DIFF_REVIEW after it has been reviewed
by user. It uses the `toDiff` list in the `install` function.
- Add utils function related to handling this change in download.go.

This change only consider diff reviewed to update the YAY_DIFF_REVIEW ref.
If a user does not enable review, the ref will not be updated and the
user will be prompted for review when he enables diff review.

It is my first time submitting change to an open source project. If anything is wrong, feel free to correct me! :)

Signed-off-by: Loic Reyreaud <reyreaud.loic@gmail.com>

### CODE REVIEW

**Comment by Jguer** [comment]
Hey, thanks for the time put into this, I'll review it as soon as possible.

**Comment by reyreaud-l** [comment]
Made a couple of force push to rebase the branch and resolve merge conflict, as well as GPG sign the commit.

**Comment by Jguer** [comment]
Tested on package `yay-git`. Manually inserting ref showed it works as desired, clean install works.

Seems to be working as intended.

**Comment by Jguer** [comment]
Seems to be working correctly still, let's merge it.
If you would like to leave some suggestions on how to unit test it or functionality test it I'm all ears.

Either way, thank you for your contribution, I hope to see more contributions from you in the future

**Comment by Morganamilo** [comment]
I've missed my chance now but I'd much prefer the ref name be something generic like `AUR_DIFF` so that if other AUR helpers decide to use this method, cache dirs can be shared and this would apply to both helpers.

**Comment by Jguer** [comment]
That's a cool idea actually. https://github.com/AladW/aurutils/commit/6ffd3958c3bf853904d88e1296080ed9a2ecdbd7 uses `AURUTILS_SEEN` it seems. Until the new version of yay is packaged we can change this with no problem.

**Comment by reyreaud-l** [comment]
I agree, I will check other AUR helpers see if we can find a common pattern for naming these refs. If not I will use AURUTILS_SEEN. I'll open another PR soon.

**Pull request merged**
