### PR TITLE
 Add --rebuild flag

### PR DESCRIPTION
**Pull request by Morganamilo**
Similar to the --redownload flag, when specifed targets will be rebuilt
even if an up to date version is cached. --rebuildall can be used to
ensure uninstalled dependencies are rebuilt as well.

Additionally, unlike --redownload there is also --rebuildtree. This
causes a rebuild and reinstall of a package and all of it's dependencies
recursivley. This is designed for when a libary updae, breaks an
installed AUR package due to a partial upgrade. polybar is a common
example

--rebuild allows you to easily skip the cache and rebuild against a newer
libary version. --rebuildtree is a more nuclear option where you can
rebuild the whole dependency tree.

This is my purposed fix for #87 It does not really do what the issue asks because that would be a project in itself. These flags should provide an easier way to mange such things manually though.

### CODE REVIEW

**Comment by Jguer** [comment]
I like, haven't reviewed the code but cmus-git is always breaking due to the lack of this

**Comment by Morganamilo** [comment]
One thing I'm not too sure on is the name. I went with `--rebuildchain` for some reason, although thinking about it most of the internal code uses the word tree. So for sake of consistency I'm thinking of changing it to `--rebuildtree`. Do you have a preference?

**Comment by Jguer** [comment]
`--rebuildtree` sounds more accurate

**Comment by Morganamilo** [comment]
Alright, changed.

**Pull request merged**
