### PR TITLE
Improve conflict handling

### PR DESCRIPTION
**Pull request by Morganamilo**
Renable conflict checking, was disabled for testing, forgot to reenable
Use pacman --ask to remove conflicting packages, dont do it directly.
Say what each package conflicts with
Check for conflicts before aking for clean build

Reverse conflict are still not checked

Example output:
image

Relies on Jguer/go-alpm#4

### CODE REVIEW

**Comment by Morganamilo** [comment]
@AladW You closed the talk section so I'll just link you here. This commit removed `-Rdd`, less that 10 days after it was added in the first place.

> I pointed this out and was ignored

 I don't remember you pointing it out anywhere here. May you're confused with trizen? https://github.com/trizen/trizen/commit/ba687bc3c3e306e6f3942e95f825ed6a55d3ad69

**Comment by AladW** [comment]
I mentioned in the comments of the commit adding -Rdd

**Comment by Morganamilo** [comment]
This commit? https://github.com/Jguer/yay/commit/28515c8b

**Comment by AladW** [comment]
right, https://github.com/Jguer/yay/commit/28515c8beb5da851f8c37bf7aa70e210e0e2163d?diff=unified#r27587686

**Comment by Morganamilo** [comment]
Ah right, was in the middle of the page so I missed it some how. Sorry about that. Would like to point out that It was removed the day after that comment.

**Comment by AladW** [comment]
Changed the entry to "partial" then for now. If #130 is implemented yay should move back in the top section of the table

**Comment by Morganamilo** [comment]
#146 Is fixed in the git only, that's why I had not changed the wiki myself. We're due a release in a day so I don't know if it's worth the effort of changing it back.

**Comment by AladW** [comment]
Eh, don't worry about it. Thanks for making those improvements.

**Comment by AladW** [comment]
Oh, I see what you mean now. The wiki table used to have entries by name only, not actual AUR packages. So it should probably reflect how the release version performs as you say.

As I agree it's not worth changing back the colors, I've just added a "yay-git" to the entry.

**Comment by Morganamilo** [comment]
Yeah that seems like the best way to do it. As long as the table doesn't end up getting flooded with helper-git* exceptions dotted around.

**Pull request merged**
