### PR TITLE
Localizing yay!

### PR DESCRIPTION
**Pull request by samosaara**
I pretend to start to support a localization system to yay as a followup to #90, currently it is simply a stub without the strings actually put in place. But I wanted to open the PR so we can discuss on the how, and also for me to be able to build with your guys feedback.

I've looked on specialized ways to translate like GNU gettext, XML resources, but given go build and distribution mechanisms, and the ecosystem of the tools that didn't seem very mature, without even mentioning the inherent complexity such big tools bring, I chose to do it programmatically, with go's map literals. 

The obvious downside of that approach is that it might be too complex to translators to contribute, given they needed to understand (even though simple) golang's syntax, and (AFAIK, never used them) we also won't be able to tap into the established ecosystem of translation crowd sourcing tools such as [pootle](http://pootle.translatehouse.org/) (even though an argument could be made that such tools could be also be too complex in and of themselves).

But anyway I did come up with a simple stub in go, any comments, thoughts? May I actually start mapping the strings?

### CODE REVIEW

**Comment by Morganamilo** [comment]
I still think this is a bit overly complicated and might be a way to halt development. If some one adds a feature that has new text what do we do? refuse the feature until we translate all the strings for the feature? Use the English string as a fallback and add translations over time? If some one wants to tweak the phrasing of something then they will also have to do this in x more languages.

Down the line it could be a good idea when Yay is more mature and feature complete and less likely to change.

As for my general thoughts on implementation the first problem I see is we have `go-alpm` `gopkgbuild` `aur` as dependencies and most of the time if any of them fail we take the error string it provides verbatim. So we would have to deal with translating the dependencies or generating out own string on an API error.

Ignoring the problems my thoughts on implementation off the top of my head would be a language struct.
```go
type language struct {
    NumbersToInstall string
    CantFindPackage string
    ....
}
```

Which we build for each language.

```go
english := language {
    NumbersToInstall: "Type numbers to install. Separate each number with a space.",
    CantFindPackage: "Cant find package %s",
    ....
}
```

Then detect the language we require and set that globally.

```go
currentLang = getLang()
```

Where currentLang would be a pointer to the English struct if we were using English.

Then using it would be as simple as.

```go
fmt.Printf(currentLang.CantFindPackage, pkg)
```

**Comment by samosaara** [comment]
Oh please, don't get me wrong, I would hate to transform a feature into a chore, I'm definitely not trying to overly-complicate the system or anything, I intend it to make as unobtrusive as possible, and just falling back to english is indeed my number one way to do that.

The system you proposed was pretty much exactly like my stub implementation, just that I preferred a hash map over a structure value because it is much, much more flexible, like allowing to do stuff like fallback-language even though it doesn't provide 'type safety'. or convenient auto complete.

**Comment by Morganamilo** [comment]
With the fallback method I feel like we would end up with a complete English translation and all other translations half done. I don't really know how many people use Yay so I cant really say what the size of the user-base is but going from the GitHub contributors getting translators might be hard. Verifying translations would also be very difficult.

I don't think there's enough gain to warrant a system like this. But it might be good to have this in a separate branch so it can be developed for when it's ready and needed. So feel free to develop it further, I might even contribute to the framework but I'll be unable to translate anything. I'm not an authority on this project though just voicing my views.

**Comment by Morganamilo** [comment]
Also a bit early for implementation but I would probably much prefer structs over maps for this, both for stricter compile time checks and speed. Fallbacks could still be done as.

```go
french := language {
    NumbersToInstall: "some french stuff",
    CantFindPackage: english.CantFinePackage //fallback
    ....
}
```

Although that would call the string to be duplicated because they are pass by value so maybe its not the best solution.

**Comment by samosaara** [comment]
> I feel like we would end up with a complete English translation and all other translations half done.

Yes I also agree that is very likely. But I can't see why this would be bad... people would still have a mostly localized yay that can use even though it is not translated fully. Something is better than nothing.

Well, I still believe that a structure are way too limiting (and also very redundant and verbose to implement fallbacks), just for the sake of being convenient, well if you still want correctness, we could create an father object containing all the possible translation keys as in a ENUM

**Comment by simon04** [comment]
Why not make use of [an existing library](https://github.com/search?o=desc&q=i18n+language%3Ago&s=stars&type=Repositories) such as https://github.com/nicksnyder/go-i18n?

**Comment by Jguer** [comment]
I agree on pulling a new lib for localisation, I think shell completions are not a priority right now to translate (and they're slow as it is already)

**Comment by Morganamilo** [comment]
What about this? https://github.com/leonelquinteros/gotext

**Comment by Jguer** [comment]
From my research I also concluded that would be the best one (sweet mother of bloat).

**Comment by Morganamilo** [comment]
Well if you care about bloat so much we can always rewrite Yay in c. ;)

I'll look into setting up some sort of working example.

**Comment by Jguer** [comment]
I know, I know, no point crying over one more lib when you have ~600 MiB of `noto-fonts` installed

**Comment by Jguer** [comment]
Closing this in favour of #342

**Pull request closed without merging**
