### PR TITLE
Print each out of date package at new line

### PR DESCRIPTION
**Pull request by AlexWayfer**
Before:

image

After:

image

### CODE REVIEW

**Comment by Jguer** [comment]
I feel it's too vertical, I like readability but I hate scrolling up. I feel it's fine as is

**Comment by AlexWayfer** [comment]
Okay. :pensive:

**Comment by Jguer** [comment]
Haha, don't feel bad on it, most of your pull request have been really good. As a further justification, I only had time to go search today but I remembered #331 which dealt with unactionable warning, this would just exacerbate the problem for some of these users

**Comment by AlexWayfer** [comment]
Thank you, I understood.

**Pull request closed without merging**
