### PR TITLE
Sort uplice by pacman repo order

### PR DESCRIPTION
**Pull request by Morganamilo**
This was implemented before but looks like it was taken out at some point.

### CODE REVIEW

**Comment by Morganamilo** [comment]
Whatever the issue is with the linting. My local `make fmt` doesn't see or fix it.

**Comment by Jguer** [comment]
Probably a distraction during refactoring, good to see you back, 

`make lint` will probably pick up the issue with the linting phase

**Comment by mindyourlifeguide** [comment]
@Jguer  Please approve this pull request.

**Review by Jguer — CHANGES_REQUESTED** [review]
Should just require the linting fix and all good

**Comment by Morganamilo** [comment]
Woo finally got the tests to pass. Quite annoying that the tests don't seem to run locally cause I run pacman-git.

**Review by Jguer — APPROVED** [review]
Seems all good, I'll merge it and check why an old version of go-alpm gets pulled as an indirect

**Pull request merged**
