### PR TITLE
feat(local_install): add choice menu for yay -Bi

### LINKED ISSUE #1899: [yay v12] Selective local install for meta package
### Is your feature request related to a problem? Please describe.

I am using the `next` branch using the `yay-git` AUR package.
I wanted to install the new version of [`postfix`](https://archlinux.org/packages/extra/x86_64/postfix/) 3.7.4 that has been released upstream but not on Arch Linux.
To do that:
```
yay -G postfix
cd postfix/repos/extra-x86_64 
vim PKGBUILD
```
And replace
```
pkgver=3.7.3
pkgrel=4
```
by:
```
pkgver=3.7.4
pkgrel=1
```

And remove `linux6.patch` from `source`.
And remove from `prepare()`:
```
  # support Linux 6.x
  patch -Np2 -d $pkgbase-$pkgver -i ../linux6.patch
```
Exit `vim` with `:wq`.

Then:
```
rm linux6.patch
updpkgsums
makepkg --printsrcinfo > .SRCINFO
git add PKGBUILD .SRCINFO linux6.patch
git commit -m 'postfix 3.7.4 release'
gpg --recv-keys 0C0B590E80CA15A7
cd ..
yay -Bi extra-x86_64 
```

### Describe the solution you'd like

1. When `yay -Bi` happens,  the local changes should be taken but they are reversed if `git add` and `git commit` have not been used after the local changes.

2. When I use `yay -Bi`, I think `debugedit` is a dependency? Can you add it to `yay` AUR package?
And I'll ask as well to the maintainer of the `yay-git` AUR package, but if it is a necessary dep.

```
  -> Nettoyage des symboles inutiles dans les fichiers binaires et les bibliothèques…
/usr/share/makepkg/tidy/strip.sh: ligne 48: debugedit : commande introuvable
/usr/share/makepkg/tidy/strip.sh: ligne 48: debugedit : commande introuvable
/usr/share/makepkg/tidy/strip.sh: ligne 48: debugedit : commande introuvable
/usr/share/makepkg/tidy/strip.sh: ligne 48: debugedit : commande introuvable
/usr/share/makepkg/tidy/strip.sh: ligne 48: debugedit : commande introuvable
/usr/share/makepkg/tidy/strip.sh: ligne 48: debugedit : commande introuvable
/usr/share/makepkg/tidy/strip.sh: ligne 48: debugedit : commande introuvable
```

3. We should be able to do a selective local install of a meta package
```
yay -Bi extra-x86_64 -m postfix,postfix-mysql
```

Instead of having offered every _subpackage_:
```
Paquets (8) postfix-3.7.4-1  postfix-cdb-3.7.4-1  postfix-ldap-3.7.4-1  postfix-lmdb-3.7.4-1  postfix-mysql-3.7.4-1  postfix-pcre-3.7.4-1  postfix-pgsql-3.7.4-1
            postfix-sqlite-3.7.4-1

Taille totale installée :      4,62 MiB
Taille de mise à jour nette :  0,19 MiB

:: Procéder à l’installation ? [O/n]  
```

### Describe alternatives you've considered

`yay -S postfix`
And editing the PKGBUILD, which is nice, but I think the other option should exist, especially when you create locally your own meta packages from scratch and want to selectively install some of the _subpackages_ but not all.

Furthermore, it does not seem to work: I am not able to edit the PKGBUILD during a *reinstall* process.
See: https://github.com/Jguer/yay/issues/1900

### PR DESCRIPTION
**Pull request by Jguer**
Fixes https://github.com/Jguer/yay/issues/1899

image

### CODE REVIEW

**Comment by HLFH** [comment]
Thanks @Jguer!!

**Comment by Jguer** [comment]
No problem @HLFH , if you find anything weird with the new `-Bi` option, don't hesitate to report, I expected there's still a lot to polish.

**Comment by HLFH** [comment]
@Jguer Thanks a lot. Still does not work for two reasons, one primary one and one secondary reason listed on this issue: https://github.com/Jguer/yay/issues/1905. Separately, you can also have a look at: https://github.com/Jguer/yay/issues/1900. Thanks!

**Comment by sirianni** [comment]
Thanks for adding this, but I'm confused as to how it's supposed to work.

I downloaded an out of date package from AUR and modified it with new versions.  When I ran `yay -Bi` it somehow seemed to revert my changes and build and install the old version of the package.  I committed my changes to git and same behavior.

**Pull request merged**
