### PR TITLE
Added --copyleft-only argument

### PR DESCRIPTION
**Pull request by 0v3rl0w**
I thought about people that are using distros like Parabola. So I decided to code a kind of arguments to check if a package is copylefted or not. I don't have all the copyleft license in the code, it will need to complete.

Any comments and hints are welcomed

### CODE REVIEW

**Comment by Morganamilo** [comment]
This seems like a weirdly specific thing to add to yay. Parabola patches pacman already iirc. Wouldn't it be better for them to patch makepkg on their end? That would then work with any pkgbuild, from any source, with any helper.

**Comment by 0v3rl0w** [comment]
I've never tried parabola, but I tought that could be a good idea to implement this, after if you think that's not that great, no problem ^^

**Comment by Morganamilo** [comment]
Actually thinking about it this could possibly work as a libmakepkg drop in. So no need to patch pacman. If you're truly interested in the feature that's probably the way to go. I'd rather not feature creep yay any more.

**Comment by 0v3rl0w** [comment]
I think I don't really understand your thought

**Comment by Morganamilo** [comment]
makepkg supports drop in files to add functionality. That would probably be the way to implement this.

**Comment by 0v3rl0w** [comment]
Ok I see Thank you

**Comment by AladW** [comment]
Man, reading these reports is more fun than any soap opera.

**Pull request closed without merging**
