### PR TITLE
fix: use positional argument for "providers available" translation

### LINKED ISSUE #2517: Korean translations (ko.po) not properly formatted
### Affected Version

yay v12.4.2 - libalpm v15.0.0

### Describe the bug

```
📦[scarf@arch-distrobox yay]$ LANG=ko_KR.UTF-8 yay -S tlrc
:: %!s(int=2)에 사용할 수 있는 &{%!d(string=cargo) %!d(string=) %!d(string=) 7059752343256422140 1}개 공급자가 있습니다:
:: 저장소 extra
    1) rust 2) rustup 

숫자를 입력하세요 (기본값=1): 
==> ^C
📦[scarf@arch-distrobox yay]$ LANG=c yay -S tlrc
:: There are 2 providers available for cargo:
:: Repository extra
    1) rust 2) rustup
```

### Reproduction Steps

1. follow https://github.com/Jguer/yay?tab=readme-ov-file#source
2. run `LANG=ko_KR.UTF-8 yay -S tlrc`
3. the formatting is not properly applied unlike english one.

https://github.com/Jguer/yay/blob/138c2dd6cdf1a3738ee18f6bf94c1e8c37e15dc4/po/ko.po#L433-L435

### Expected behavior

expected: `cargo에 사용할 수 있는 2개 공급자가 있습니다:`
actual: `%!s(int=2)에 사용할 수 있는 &{%!d(string=cargo) %!d(string=) %!d(string=) 7059752343256422140 1}개 공급자가 있습니다:`

### Output

```sh
{
        "aururl": "https://aur.archlinux.org",
        "aurrpcurl": "https://aur.archlinux.org/rpc?",
        "buildDir": "/home/scarf/.cache/yay",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "redownload": "no",
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "searchby": "name-desc",
        "gitflags": "",
        "removemake": "ask",
        "sudobin": "sudo",
        "sudoflags": "",
        "version": "12.4.2",
        "requestsplitn": 150,
        "completionrefreshtime": 7,
        "maxconcurrentdownloads": 1,
        "bottomup": true,
        "sudoloop": false,
        "timeupdate": false,
        "devel": true,
        "cleanAfter": false,
        "keepSrc": false,
        "provides": true,
        "pgpfetch": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": true,
        "useask": false,
        "batchinstall": false,
        "singlelineresults": false,
        "separatesources": true,
        "debug": false,
        "rpc": true,
        "doubleconfirm": true,
        "rebuild": "no"
}
```

### PR DESCRIPTION
**Pull request by scarf005**
fixes #2517.

<details><summary>regexes used (for future reference)</summary>
<p>

for go, `en.po`, `sk.po`:
```po
msgid "There are %d providers available for %s:"
```
```po
msgid "There are %1$d providers available for %2$s:"
```
for `cs.po`, `ko.po`, `tr.po`:
```po
msgid "There are %d providers available for %s:"\nmsgstr "(.*)%s(.*)%d(.*)"
```
```po
msgid "There are %1$d providers available for %2$s:"\nmsgstr "$1%2$s$2%1$d$3"
```
everything else:
```po
msgid "There are %d providers available for %s:"\nmsgstr "(.*)%d(.*)%s(.*)"
```
```po
msgid "There are %1$d providers available for %2$s:"\nmsgstr "$1%1$d$2%2$s$3"
```

</p>
</details>

### CODE REVIEW

**Review by Jguer — APPROVED** [review]
Thanks for the PR @scarf005!

**Comment by Jguer** [comment]
Seems there's some issues with the library @scarf005

**Comment by scarf005** [comment]
```
pkg/db/ialpm/alpm.go:179:77: github.com/leonelquinteros/gotext.Get format %1$ has unknown verb $
FAIL	github.com/Jguer/yay/v12/pkg/db/ialpm [build failed]
	github.com/Jguer/yay/v12/pkg/db/mock		coverage: 0.0% of statements
# github.com/Jguer/yay/v12/pkg/dep
# [github.com/Jguer/yay/v12/pkg/dep]
pkg/dep/dep_graph.go:726:77: github.com/leonelquinteros/gotext.Get format %1$ has unknown verb $
ok  	github.com/Jguer/yay/v12	1.092s	coverage: 38.2% of statements
ok  	github.com/Jguer/yay/v12/pkg/completion	1.027s	coverage: 38.0% of statements
FAIL	github.com/Jguer/yay/v12/pkg/dep [build failed]
```

not sure why linter is complaining at `gotext.Get` format string.

**Comment by scarf005** [comment]
found out that go positional strings use different notation(`[1]`) than C(`1$`): https://github.com/leonelquinteros/gotext/issues/101#issuecomment-2515174987 
applied fix and force pushed.

**Comment by scarf005** [comment]
@Jguer could you re-run the workflow?

**Review by Jguer — APPROVED** [review]

**Comment by Jguer** [comment]
That's really cool, TIL. Thanks for checking!

**Pull request merged**
