### PR TITLE
Concurrent PKGBUILD source download

### PR DESCRIPTION
**Pull request by Jguer**
Implements #915

### CODE REVIEW

**Comment by Morganamilo** [comment]
Does this ensure deps are installed first?

**Comment by Jguer** [comment]
> Does this ensure deps are installed first?

This only changes the way `makepkg --verifysource -Ccf` is run, not the install logic itself so it should be ok for now

**Comment by Morganamilo** [comment]
No, deps are needed before sources are downloaded. Git is a good example, custom dlanglets also pop up sometimes.

**Comment by Jguer** [comment]
> No, deps are needed before sources are downloaded. Git is a good example, custom dlanglets also pop up sometimes.

This patch only replaces an existing for cycle with no return for a concurrent for cycle, unless the `bases []dep.Base` order is important I see no issue with it even in testing. Is `bases` order sensitive?

**Comment by Morganamilo** [comment]
Ah I remember now. Yay already does the wrong thing. Now it just does the wrong thing in parallel :P

See https://github.com/Jguer/yay/issues/1448

**Comment by SampsonCrowley** [comment]
Don't be such a sourpuss. this is a big performance improvement for the current process. *when* you submit a PR for your suggested change to the build process you can adapt it to be able to download deps first then main packages. Concurrent source downloading is a feature that the majority have been asking for and this is compatible with how things are already handled. Your issues are with edge cases and custom downloaders

**Comment by Morganamilo** [comment]
Anyway the proper solution is to queue only if deps are satisfied

so for packages to install -> pick out ones with all deps satisfied -> push to download queue

if download queue is empty then build and install packages in queue.

This is similar to how batch install works so the core logic should already be there.

**Comment by Jguer** [comment]
> Ah I remember now. Yay already does the wrong thing. Now it just does the wrong thing in parallel :P
> 
> See #1448

:) Exactly, the block is tested and will just need to be moved once the "install" is replacing with a pulling system instead of a pushing system

**Pull request merged**
