### PR TITLE
Filter out yay command line options

### LINKED ISSUE #122: Argumment parsing passing yay options to pacman
yay config options are being carried over to pacman on some operations when they should be parsed by yay.

Expected:
`yay -Syu --devel` 

Actual Result:
`pacman: unrecognized option '--devel'`

Workaround:
`yay -Y --devel`
`yay -Syu`

### PR DESCRIPTION
**Pull request by Morganamilo**
Fixes #122. funnily enough I already built a function to do this I must have just forgotten to call it.

### CODE REVIEW

**Comment by Jguer** [comment]
Thanks for the quick fix, I figured you would know better where to touch it up.

**Comment by Morganamilo** [comment]
Just realised this doesn't really fix it fully. I'll send another pr soon.

**Comment by Jguer** [comment]
Weird, tested in the go folder with `./yay -Syu --devel` and it worked and now in the package it fails.

**Comment by Morganamilo** [comment]
It filters it out a little too much. Basically it just ignores it and takes the config file's value.

**Comment by Morganamilo** [comment]
Yes that should be a thing. Not sure how to do it for web related stuff though but I could do it for the parser and all that.

**Comment by Jguer** [comment]
If you're able to do it for the parser that would be great

**Comment by Morganamilo** [comment]
Sure I'll try. I've never actually done testing in go so I'll just be copying the existing test format.

**Pull request merged**
