### PR TITLE
Add SudoBin and SudoFlags

### LINKED ISSUE #1031: [Feature]- Can we get a terminal bell before sudo prompt on long builds.
#### Affected Version
yay v9.3.1 - libalpm v11.0.3
#### Steps to reproduce

1. build large package such as linux-ck
2. Miss sudo prompt 
3. have to redo the intial build process
FEATURE Request

Cam we get a terminal bell before the sudo prompt shows up (especially after a long build) to prompt us that our password has to be entered.

### PR DESCRIPTION
**Pull request by Morganamilo**
Same as #492 but with https://github.com/Jguer/yay/pull/942#discussion_r294338344.

Fixes #1031

### CODE REVIEW

**Comment by Jguer** [comment]
I would have added a warning pre sudo call detailing the location of `sudobin` if it's different from `/usr/bin/sudo`

**Comment by Morganamilo** [comment]
Why? We don't do it with any other commands.

**Comment by Jguer** [comment]
Because changing yay's sudo bin and flags can potentially allow the execution of other commands as root. 
If we can't prevent it, at least a small warning would be nice.

**Comment by Morganamilo** [comment]
I guess. But a malicious program could instead change pacmanbin to a script that prompts you for your password or makes a call to sudo. It could also place a sudo binary somewhere in home and add it to path. Hell it could probably redirect all your input to a file or log your keys.

So I don't really think sudo specifically makes it any less secure.

**Comment by Morganamilo** [comment]
Surely you would have to impede the user though by adding a prompt. Otherwise you're adding a warning but still calling the potentially malicious script right after.

**Comment by Jguer** [comment]
In case of sudo commands (without `NOPASSWD`) or malicious sudo asking for a password, it will be prompting right below for said password. 

In this scenario you're assuming user level is already compromised so executing a malicious script just in the user directories would be out of scope already.

**Comment by Morganamilo** [comment]
Isn't the entire point of the warning for the case there's a malicious script? Anyway my point is the entire thing is out of scope.

**Pull request merged**
