### PR TITLE
Clone ABS/AUR Git repository instead of tarball

### PR DESCRIPTION
**Pull request by simon04**
Meant for discussion. Instead of downloading and unpacking the package source tarball, clone the corresponding Git repository. Inspired by https://github.com/falconindy/asp. Adds `git` as package dependency.

### CODE REVIEW

**Comment by Morganamilo** [comment]
Instead of ripping out the old system I would rather this be a config option.

**Comment by Jguer** [comment]
Same, would also prefer this to be an option, I know that tarballs are meant to disappear soon (if memory serves correctly) but I still prefer them.

**Comment by Morganamilo** [comment]
Also how does this handle migrating. If i have a package that I installed using the tarball method then switch to the git method will it handle it correctly?

**Comment by Morganamilo** [comment]
Do you plan on going anywhere with this? I might pick up on it myself otherwise. Add the config option and other fixes.

**Comment by Jguer** [comment]
I've been playing around with git cloning and git pulling for updates in a few branches, I think we can roll it out as an option after the maintenance.

**Comment by Jguer** [comment]
Closing this in favour of #297

**Pull request closed without merging**
