### PR TITLE
 Parallelize pkgbuild download and use MultiError

### PR DESCRIPTION
**Pull request by Morganamilo**

### CODE REVIEW

**Comment by AladW** [comment]
Last I tried this, it failed in mysterious ways when cloning over `ssh`. I guess if you only clone over https that doesn't matter, unless you change `origin` later I guess.

More generally I don't really see the benefit - AUR repos are of minimal size and if something hangs with 1 `git` process, it probably will with a bunch also.

**Comment by Morganamilo** [comment]
I can see a noticeable difference for a large amount of packages, although I guess that's not the most command occurrence. Plus you own `aur fetch` runs through parallel iirc?

**Comment by AladW** [comment]
Yeah. I just throw stuff at the wall in `aurutils-git`, though, probably unlike `yay`. So it might be worth testing before merging this

**Comment by Morganamilo** [comment]
Honestly I didn't even realise you can clone any package over ssh, I assumed it would give you a permission error if you're not the maintainer.

Still we do not offer the option to clone over ssh so if it is totally borked then I won't mind just saying that it's unsupported.

BTW any reason there's no git:// access point?

**Comment by Morganamilo** [comment]
Annnddd gendb just dropped from 20 seconds to 1 second.

**Comment by c0d3z3r0** [comment]
Tested this but got maaaaany errors like these:

~~~
goroutine 535 [running]:
runtime.throw(0x73a4ee, 0xd)
	/usr/lib/go/src/runtime/panic.go:616 +0x81 fp=0xc42049ad00 sp=0xc42049ace0 pc=0x42fc31
runtime.evacuate_faststr(0x6e6be0, 0xc4205fe090, 0x0)
	/usr/lib/go/src/runtime/hashmap_fast.go:1186 +0x490 fp=0xc42049adb0 sp=0xc42049ad00 pc=0x4137d0
runtime.growWork_faststr(0x6e6be0, 0xc4205fe090, 0x0)
	/usr/lib/go/src/runtime/hashmap_fast.go:1145 +0x61 fp=0xc42049add8 sp=0xc42049adb0 pc=0x4132f1
runtime.mapassign_faststr(0x6e6be0, 0xc4205fe090, 0xc4205761c9, 0x30, 0xc420235f80)
	/usr/lib/go/src/runtime/hashmap_fast.go:718 +0x351 fp=0xc42049ae48 sp=0xc42049add8 pc=0x4120c1
main.updateVCSData.func1(0x0, 0x0, 0xc4205761bdfatal: remote error: 
  Repository not found.
, 0x3c)
	/home/c0d3/src/yay.git/vcs.go:133 +0x201 fp=0xc42049afc0 sp=0xc42049ae48 pc=0x690511
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42049afc8 sp=0xc42049afc0 pc=0x45b6e1
created by main.updateVCSData
	/home/c0d3/src/yay.git/vcs.go:148 +0x181

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc42009907c)
	/usr/lib/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc420099070)
	/usr/lib/go/src/sync/waitgroup.go:129 +0x72
main.createDevelDB(0xc4200a0180, 0xc420055df8)
	/home/c0d3/src/yay.git/vcs.go:59 +0x513
main.handleYay(0x734296, 0x1)
	/home/c0d3/src/yay.git/cmd.go:220 +0x1b7
main.handleCmd(0x0, 0x0)
	/home/c0d3/src/yay.git/cmd.go:162 +0x2ab
main.main()
	/home/c0d3/src/yay.git/main.go:239 +0x2b3

goroutine 770 [IO wait]:
internal/poll.runtime_pollWait(0x7f211c2087f0, 0x72, 0xc420a56ce8)
	/usr/lib/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4202306f8, 0x72, 0xffffffffffffff01, 0x778720, 0x8bc6e0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4202306f8, 0xc420623e01, 0x200, 0x200)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4202306e0, 0xc420623e00, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:157 +0x17d
os.(*File).read(0xc42000e888, 0xc420623e00, 0x200, 0x200, 0xc420623e00, 0x0, 0x0)
	/usr/lib/go/src/os/file_unix.go:226 +0x4e
os.(*File).Read(0xc42000e888, 0xc420623e00, 0x200, 0x200, 0x0, 0x0, 0xc420a56e60)
	/usr/lib/go/src/os/file.go:107 +0x6a
bytes.(*Buffer).ReadFrom(0xc4201eb0a0, 0x777de0, 0xc42000e888, 0x7f211c3f6a10, 0xc4201eb0a0, 0x1)
	/usr/lib/go/src/bytes/buffer.go:205 +0xa0
io.copyBuffer(0x777880, 0xc4201eb0a0, 0x777de0, 0xc42000e888, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:386 +0x31a
io.Copy(0x777880, 0xc4201eb0a0, 0x777de0, 0xc42000e888, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:362 +0x5a
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/usr/lib/go/src/os/exec/exec.go:275 +0x4d
os/exec.(*Cmd).Start.func1(0xc420633340, 0xc420227be0)
	/usr/lib/go/src/os/exec/exec.go:396 +0x27
created by os/exec.(*Cmd).Start
	/usr/lib/go/src/os/exec/exec.go:395 +0x5df

goroutine 704 [IO wait]:
internal/poll.runtime_pollWait(0x7f211c3faa80, 0x72, 0xc4204bfce8)
	/usr/lib/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4204c8478, 0x72, 0xffffffffffffff01, 0x778720, 0x8bc6e0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4204c8478, 0xc4203df601, 0x200, 0x200)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4204c8460, 0xc4203df600, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:157 +0x17d
os.(*File).read(0xc42009c510, 0xc4203df600, 0x200, 0x200, 0xc4203df600, 0x0, 0x0)
	/usr/lib/go/src/os/file_unix.go:226 +0x4e
os.(*File).Read(0xc42009c510, 0xc4203df600, 0x200, 0x200, 0xc4204bfe58, 0x498bdc, 0xc4204bfe60)
	/usr/lib/go/src/os/file.go:107 +0x6a
bytes.(*Buffer).ReadFrom(0xc4205ab420, 0x777de0, 0xc42009c510, 0x7f211c3f6a10, 0xc4205ab420, 0xc4204bfe01)
	/usr/lib/go/src/bytes/buffer.go:205 +0xa0
io.copyBuffer(0x777880, 0xc4205ab420, 0x777de0, 0xc42009c510, 0x0, 0x0, 0x0, 0xc4203e70e0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:386 +0x31a
io.Copy(0x777880, 0xc4205ab420, 0x777de0, 0xc42009c510, 0x40a1a5, 0xc420698240, 0xc4204bffb0)
	/usr/lib/go/src/io/io.go:362 +0x5a
os/exec.(*Cmd).writerDescriptor.func1(0xc420698240, 0xc4204bffb0)
	/usr/lib/go/src/os/exec/exec.go:275 +0x4d
os/exec.(*Cmd).Start.func1(0xc4202b11e0, 0xc4201ec680)
	/usr/lib/go/src/os/exec/exec.go:396 +0x27
created by os/exec.(*Cmd).Start
	/usr/lib/go/src/os/exec/exec.go:395 +0x5df

goroutine 683 [IO wait]:
internal/poll.runtime_pollWait(0x7f211c3f7d40, 0x72, 0xc4204b9ce8)
	/usr/lib/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42032f0a8, 0x72, 0xffffffffffffff01, 0x778720, 0x8bc6e0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42032f0a8, 0xc4205c3e01, 0x200, 0x200)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42032f090, 0xc4205c3e00, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:157 +0x17d
os.(*File).read(0xc42000e608, 0xc4205c3e00, 0x200, 0x200, 0xc4205c3e00, 0x0, 0x0)
	/usr/lib/go/src/os/file_unix.go:226 +0x4e
os.(*File).Read(0xc42000e608, 0xc4205c3e00, 0x200, 0x200, 0x1d, 0x3e, 0xc4204b9e60fatal: remote error: 
  Repository not found.
fatal: remote error: 
  Repository not found.
)
	/usr/lib/go/src/os/file.go:107 +0x6a
bytes.(*Buffer).ReadFrom(0xc4201ea700, 0x777de0, 0xc42000e608, 0x7f211c3f6a10, 0xc4201ea700, 0x1)
	/usr/lib/go/src/bytes/buffer.go:205 +0xa0
io.copyBuffer(0x777880, 0xc4201ea700, 0x777de0, 0xc42000e608, 0x0, 0x0, 0x0, 0xc42027be90, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:386 +0x31a
io.Copy(0x777880, 0xc4201ea700, 0x777de0, 0xc42000e608, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:362 +0x5a
os/exec.(*Cmd).writerDescriptor.func1(0x6c4a60, 0xc4203601b8)
	/usr/lib/go/src/os/exec/exec.go:275 +0x4d
os/exec.(*Cmd).Start.func1(0xc420063600, 0xc420226e80)
	/usr/lib/go/src/os/exec/exec.go:396 +0x27
created by os/exec.(*Cmd).Start
	/usr/lib/go/src/os/exec/exec.go:395 +0x5df

goroutine 37 [IO wait]:
internal/poll.runtime_pollWait(0x7f211c3dbf00, 0x72, 0xc420463858)
	/usr/lib/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420168518, 0x72, 0xffffffffffffff00, 0x778720, 0x8bc6e0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420168518, 0xc4203d4000, 0x1000, 0x1000)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420168500, 0xc4203d4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc420168500, 0xc4203d4000, 0x1000, 0x1000, 0x0, 0x1, 0x100000000000000)
	/usr/lib/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42000e008, 0xc4203d4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc4203280c0, 0x7f211c1c5000, 0xc42000e008, 0x5, 0xc42000e008, 0xc4204d5b40)
	/usr/lib/go/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc4200e8000, 0x750017, 0xc4200e8120, 0xc420313140)
	/usr/lib/go/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc4200e8000, 0xc420334000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:1156 +0x100
bufio.(*Reader).Read(0xc420313080, 0xc4201deab8, 0x9, 0x9, 0xc420463c50, 0x461ac3, 0xc420463c60)
	/usr/lib/go/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0x777820, 0xc420313080, 0xc4201deab8, 0x9, 0x9, 0x9, 0xc4200b9601, 0xc420463d00, 0x5f1c5b)
	/usr/lib/go/src/io/io.go:309 +0x86
io.ReadFull(0x777820, 0xc420313080, 0xc4201deab8, 0x9, 0x9, 0xc420084030, 0xc420463d30, 0x5f1b6d)
	/usr/lib/go/src/io/io.go:327 +0x58
net/http.http2readFrameHeader(0xc4201deab8, 0x9, 0x9, 0x777820, 0xc420313080, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/h2_bundle.go:1517 +0x7b
net/http.(*http2Framer).ReadFrame(0xc4201dea80, 0xc42036e960, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/h2_bundle.go:1775 +0xa4
net/http.(*http2clientConnReadLoop).run(0xc420463fb8, 0x74fab8, 0xc420033fb8)
	/usr/lib/go/src/net/http/h2_bundle.go:8028 +0x90
net/http.(*http2ClientConn).readLoop(0xc420332000)
	/usr/lib/go/src/net/http/h2_bundle.go:7956 +0x68
created by net/http.(*http2Transport).newClientConn
	/usr/lib/go/src/net/http/h2_bundle.go:7143 +0x65c

goroutine 566 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x37c0, 0xc420606bb0, 0x1000004, 0x0, 0x0, 0x0, 0xc4201e3000, 0x0)
	/usr/lib/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc420564c90, 0x0, 0xc420606d08, 0x4167d9)
	/usr/lib/go/src/os/wait_waitid.go:31 +0x98
os.(*Process).wait(0xc420564c90, 0x7f21221186c8, 0x0, 0xc4201d2180)
	/usr/lib/go/src/os/exec_unix.go:22 +0x3c
os.(*Process).Wait(0xc420564c90, 0xc42032ec88, 0x8ed340, 0x8ed340)
	/usr/lib/go/src/os/exec.go:123 +0x2b
os/exec.(*Cmd).Wait(0xc4202b0160, 0xc4201d2180, 0xc42032ec80)
	/usr/lib/go/src/os/exec/exec.go:461 +0x5c
main.getCommit(0xc4205765cd, 0x34, 0x734a38, 0x4, 0xc42020fea0, 0x2, 0x2, 0x2, 0x2)
	/home/c0d3/src/yay.git/vcs.go:174 +0x2be
main.updateVCSData.func1(0x0, 0x0, 0xc4205765c1, 0x40)
	/home/c0d3/src/yay.git/vcs.go:128 +0x13c
created by main.updateVCSData
	/home/c0d3/src/yay.git/vcs.go:148 +0x181

goroutine 480 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x3818, 0xc420543bb0, 0x1000004, 0x0, 0x0, 0x0, 0xc4205d4400, 0x0)
	/usr/lib/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc420688de0, 0x0, 0xc420543d08, 0x4167d9)
	/usr/lib/go/src/os/wait_waitid.go:31 +0x98
os.(*Process).wait(0xc420688de0, 0x7f2122118000, 0x0, 0xc42020e840)
	/usr/lib/go/src/os/exec_unix.go:22 +0x3c
os.(*Process).Wait(0xc420688de0, 0xc4203e6eb8, 0x8ed2c0, 0x8ed2c0)
	/usr/lib/go/src/os/exec.go:123 +0x2b
os/exec.(*Cmd).Wait(0xc4206a2420, 0xc42020e840, 0xc4203e6eb0)
	/usr/lib/go/src/os/exec/exec.go:461 +0x5c
main.getCommit(0xc420516a19, 0x2b, 0x734a38, 0x4, 0xc420235ba0, 0x2, 0x2, 0x2, 0x2)
	/home/c0d3/src/yay.git/vcs.go:174 +0x2be
main.updateVCSData.func1(0x0, 0x0, 0xc420516a0d, 0x37)
	/home/c0d3/src/yay.git/vcs.go:128 +0x13c
created by main.updateVCSData
	/home/c0d3/src/yay.git/vcs.go:148 +0x181

goroutine 412 [semacquire]:
sync.runtime_SemacquireMutex(0x906cc4, 0x0)
	/usr/lib/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0x906cc0)
	/usr/lib/go/src/sync/mutex.go:134 +0x108
sync.(*RWMutex).Lock(0x906cc0)
	/usr/lib/go/src/sync/rwmutex.go:93 +0x2d
syscall.forkExec(0xc42027bc60, 0xc, 0xc4202eb8c0, 0x6, 0x6, 0xc420293b78, 0x20, 0x0, 0xc4203d92c0)
	/usr/lib/go/src/syscall/exec_unix.go:186 +0x1f0
syscall.StartProcess(0xc42027bc60, 0xc, 0xc4202eb8c0, 0x6, 0x6, 0xc420293b78, 0x2, 0x4, 0x0, 0x0)
	/usr/lib/go/src/syscall/exec_unix.go:241 +0x64
os.startProcess(0xc42027bc60, 0xc, 0xc4202eb8c0, 0x6, 0x6, 0xc420293d20, 0xc4200e9880, 0x31, 0x31)
	/usr/lib/go/src/os/exec_posix.go:46 +0x1f1
os.StartProcess(0xc42027bc60, 0xc, 0xc4202eb8c0, 0x6, 0x6, 0xc420293d20, 0x0, 0x0, 0x4167d9)
	/usr/lib/go/src/os/exec.go:102 +0x7c
os/exec.(*Cmd).Start(0xc4203b0160, 0xc420092600, 0x30)
	/usr/lib/go/src/os/exec/exec.go:379 +0x4e6
main.getCommit(0xc4204c0404, 0x24, 0x734a38, 0x4, 0xc42020eb40, 0x2, 0x2, 0x2, 0x2)
	/home/c0d3/src/yay.git/vcs.go:160 +0x21c
main.updateVCSData.func1(0x0, 0x0, 0xc4204c03f8, 0x30)
	/home/c0d3/src/yay.git/vcs.go:128 +0x13c
created by main.updateVCSData
	/home/c0d3/src/yay.git/vcs.go:148 +0x181

goroutine 718 [IO wait]:
internal/poll.runtime_pollWait(0x7f211c3fb100, 0x72, 0xc4205b3ce8)
	/usr/lib/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42032ff08, 0x72, 0xffffffffffffff01, 0x778720, 0x8bc6e0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42032ff08, 0xc420623201, 0x200, 0x200)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42032fef0, 0xc420623200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:157 +0x17d
os.(*File).read(0xc42000e788, 0xc420623200, 0x200, 0x200, 0xc420623200, 0x0, 0x0)
	/usr/lib/go/src/os/file_unix.go:226 +0x4e
os.(*File).Read(0xc42000e788, 0xc420623200, 0x200, 0x200, 0xc4205b3e58, 0x498bdc, 0xc4205b3e60)
	/usr/lib/go/src/os/file.go:107 +0x6a
bytes.(*Buffer).ReadFrom(0xc4201eacb0, 0x777de0, 0xc42000e788, 0x7f211c3f6a10, 0xc4201eacb0, 0xc4205b3e01)
	/usr/lib/go/src/bytes/buffer.go:205 +0xa0
io.copyBuffer(0x777880, 0xc4201eacb0, 0x777de0, 0xc42000e788, 0x0, 0x0, 0x0, 0xc420308320, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:386 +0x31a
io.Copy(0x777880, 0xc4201eacb0, 0x777de0, 0xc42000e788, 0x40a1a5, 0xc42029e4e0, 0xc4205b3fb0)
	/usr/lib/go/src/io/io.go:362 +0x5a
os/exec.(*Cmd).writerDescriptor.func1(0xc42029e4e0, 0xc4205b3fb0)
	/usr/lib/go/src/os/exec/exec.go:275 +0x4d
os/exec.(*Cmd).Start.func1(0xc4206326e0, 0xc420227640)
	/usr/lib/go/src/os/exec/exec.go:396 +0x27
created by os/exec.(*Cmd).Start
	/usr/lib/go/src/os/exec/exec.go:395 +0x5df

goroutine 754 [IO wait]:
internal/poll.runtime_pollWait(0x7f211c2094f0, 0x72, 0xc4205b2ce8)
	/usr/lib/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4202303d8, 0x72, 0xffffffffffffff01, 0x778720, 0x8bc6e0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4202303d8, 0xc4205d0e01, 0x200, 0x200)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4202303c0, 0xc4205d0e00, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:157 +0x17d
os.(*File).read(0xc42000e828, 0xc4205d0e00, 0x200, 0x200, 0xc4205d0e00, 0x0, 0x0)
	/usr/lib/go/src/os/file_unix.go:226 +0x4e
os.(*File).Read(0xc42000e828, 0xc4205d0e00, 0x200, 0x200, 0xc4205b2e58, 0x498bdc, 0xc4205b2e60)
	/usr/lib/go/src/os/file.go:107 +0x6a
bytes.(*Buffer).ReadFrom(0xc4201eaee0, 0x777de0, 0xc42000e828, 0x7f211c3f6a10, 0xc4201eaee0, 0xc4205b2e01)
	/usr/lib/go/src/bytes/buffer.go:205 +0xa0
io.copyBuffer(0x777880, 0xc4201eaee0, 0x777de0, 0xc42000e828, 0x0, 0x0, 0x0, 0xc42009e7d0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:386 +0x31a
io.Copy(0x777880, 0xc4201eaee0, 0x777de0, 0xc42000e828, 0x40a1a5, 0xc42029e840, 0xc4205b2fb0)
	/usr/lib/go/src/io/io.go:362 +0x5a
os/exec.(*Cmd).writerDescriptor.func1(0xc42029e840, 0xc4205b2fb0)
	/usr/lib/go/src/os/exec/exec.go:275 +0x4d
os/exec.(*Cmd).Start.func1(0xc420632dc0, 0xc4202279a0)
	/usr/lib/go/src/os/exec/exec.go:396 +0x27
created by os/exec.(*Cmd).Start
	/usr/lib/go/src/os/exec/exec.go:395 +0x5df

goroutine 672 [IO wait]:
internal/poll.runtime_pollWait(0x7f211c207a20, 0x72, 0xc4203f0ce8)
	/usr/lib/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42009fdc8, 0x72, 0xffffffffffffff01, 0x778720, 0x8bc6e0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42009fdc8, 0xc420622801, 0x200, 0x200)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42009fdb0, 0xc420622800, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:157 +0x17d
os.(*File).read(0xc42009c430, 0xc420622800, 0x200, 0x200, 0xc420622800, 0x0, 0x0)
	/usr/lib/go/src/os/file_unix.go:226 +0x4e
os.(*File).Read(0xc42009c430, 0xc420622800, 0x200, 0x200, 0x464344, 0xc420099070, 0xc4203f0e60)
	/usr/lib/go/src/os/file.go:107 +0x6a
bytes.(*Buffer).ReadFrom(0xc4205ab110, 0x777de0, 0xc42009c430, 0x7f211c3f6a10, 0xc4205ab110, 0xc420022a01)
	/usr/lib/go/src/bytes/buffer.go:205 +0xa0
io.copyBuffer(0x777880, 0xc4205ab110, 0x777de0, 0xc42009c430, 0x0, 0x0, 0x0, 0xc4203f0f98, 0x68a9d7, 0xc420099070)
	/usr/lib/go/src/io/io.go:386 +0x31a
io.Copy(0x777880, 0xc4205ab110, 0x777de0, 0xc42009c430, 0x6, 0x9, 0xc420283470)
	/usr/lib/go/src/io/io.go:362 +0x5a
os/exec.(*Cmd).writerDescriptor.func1(0x437d18, 0x74fe68)
	/usr/lib/go/src/os/exec/exec.go:275 +0x4d
os/exec.(*Cmd).Start.func1(0xc4202b0840, 0xc4201ec200)
	/usr/lib/go/src/os/exec/exec.go:396 +0x27
created by os/exec.(*Cmd).Start
	/usr/lib/go/src/os/exec/exec.go:395 +0x5df

goroutine 728 [IO wait]:
internal/poll.runtime_pollWait(0x7f211c3fbe00, 0x72, 0xc4203f74e8)
	/usr/lib/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200bb4b8, 0x72, 0xffffffffffffff01, 0x778720, 0x8bc6e0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4200bb4b8, 0xc420623a01, 0x200, 0x200)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4200bb4a0, 0xc420623a00, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/go/src/internal/poll/fd_unix.go:157 +0x17d
os.(*File).read(0xc4205d2648, 0xc420623a00, 0x200, 0x200, 0xc420623a00, 0x0, 0x0)
	/usr/lib/go/src/os/file_unix.go:226 +0x4e
os.(*File).Read(0xc4205d2648, 0xc420623a00, 0x200, 0x200, 0x464344, 0xc420099070, 0xc4203f7660)
	/usr/lib/go/src/os/file.go:107 +0x6a
bytes.(*Buffer).ReadFrom(0xc42061a460, 0x777de0, 0xc4205d2648, 0x7f211c3f6a10, 0xc42061a460, 0xc420022a01)
	/usr/lib/go/src/bytes/buffer.go:205 +0xa0
io.copyBuffer(0x777880, 0xc42061a460, 0x777de0, 0xc4205d2648, 0x0, 0x0, 0x0, 0xc4203f7798, 0x68a9d7, 0xc420099070)
	/usr/lib/go/src/io/io.go:386 +0x31a
io.Copy(0x777880, 0xc42061a460, 0x777de0, 0xc4205d2648, 0x0, 0x0, 0xc420283350)
	/usr/lib/go/src/io/io.go:362 +0x5a
os/exec.(*Cmd).writerDescriptor.func1(0x437d18, 0x74fe68)
	/usr/lib/go/src/os/exec/exec.go:275 +0x4d
os/exec.(*Cmd).Start.func1(0xc4205ade40, 0xc4201f2ea0)
	/usr/lib/go/src/os/exec/exec.go:396 +0x27
created by os/exec.(*Cmd).Start
	/usr/lib/go/src/os/exec/exec.go:395 +0x5df
~~~

**Comment by Morganamilo** [comment]
That's annoying, I though I got all the waiting and locking right. Oh well, good thing I kept this back.

**Comment by Morganamilo** [comment]
@c0d3z3r0 What command did you run? Also does this happen every time or just sometimes?

**Comment by c0d3z3r0** [comment]
@Morganamilo Ah, I missed that line above... I just ran `yay --gendb`. This happens everytime

**Comment by Morganamilo** [comment]
Well, I'm not quite sure where the slip up is. I rebased this against master, which shouldn't really change anything. but might be worth a check to see if it still panics.

**Comment by c0d3z3r0** [comment]
I rebased this PR against master, too, before testing

**Comment by c0d3z3r0** [comment]
Yay! ;)  Works now

**Comment by Morganamilo** [comment]
Anyway, part of the reason this has been open so long is because I needed to get around to testing ssh.

Finally dong that, all I see is `ssh_exchange_identification: read: Connection reset by peer` everywhere. Guessing that's what you were on about @AladW?

**Comment by Morganamilo** [comment]
This is not finished, although there's some other stuff I want to get done first. So instead of ending up with a huge PR that goes out of scope, or dealing with huge conflicts, I'll just merge it now.

Everything seems to work as is, so no need to worry about it being in a broken state.

**Comment by Jguer** [comment]
Fair enough, in vacation with an average ping of 400ms to github at night, I'll try and keep updated on the changes

**Comment by Morganamilo** [comment]
The follow up will be to make `yay -G` use this method, instead of the current duplicated functionality. But first I'll be refactoring some stuff in install so that it all fits together better.

**Pull request merged**
