### PR TITLE
completions/fish: refine from pacman 5.2.0 and yay 9.4.2

### PR DESCRIPTION
**Pull request by akiirui**
Base [fish-shell: completions/pacman.fish: Update for pacman 5.2](https://github.com/fish-shell/fish-shell/pull/6238)

And `yay 9.4.2` options from manpages.

### CODE REVIEW

**Comment by Morganamilo** [comment]
What's up with all the quotation changes? Is that from you or upstream? My local pacman.fish seems to still have them unquoted.

I'd rather our completions purely add to pacman's and follow their conventions for diff and maintaining sake.

**Comment by akiirui** [comment]
> What's up with all the quotation changes? Is that from you or upstream? My local pacman.fish seems to still have them unquoted.
> 
> I'd rather our completions purely add to pacman's and follow their conventions for diff and maintaining sake.

Oh, that base `pacman` completion just recently merged to fish-shell/master.

I open a draft pull request before. and not marked ready for review until upstream merged `pacman.fish`.

here is diff about this `yay.fish` with upstream new `pacman.fish`.

```

**Comment by Morganamilo** [comment]
No that's fine, I just wanted to know where all the style changes came from and a smaller diff. Although it would help if you set the language to diff in your comment :P

**Comment by Morganamilo** [comment]
```diff
-complete -c $progname -s V -f -l version -d 'Display version and exit'
+complete -c $progname -s V -f -l version -n "$noopt" -d 'Display version and exit'

-complete -c $progname -n "$files" -d 'Package' -xa "$listall"
+complete -c $progname -n "$files" -d 'Package' -xa "$listpacman"
```

What's with these chanegs?

**Comment by akiirui** [comment]
```diff
-complete -c $progname -s V -f -l version -d 'Display version and exit'
+complete -c $progname -s V -f -l version -n "$noopt" -d 'Display version and exit'
```
Because `yay -V` cannot work with other primary options, like:
```
$ yay -SV
> only one operation may be used at a time
```
But `pacman` can do this.

```diff
-complete -c $progname -n "$files" -d 'Package' -xa "$listall"
+complete -c $progname -n "$files" -d 'Package' -xa "$listpacman"
```
Because `pacman -F --files` options just query in repository database. Cannot query file with AUR packages.

**Comment by Morganamilo** [comment]
Makes sense.

**Comment by KokaKiwi** [comment]
I have errors on my fish (version 3.0.2 on Arch Linux), saying `complete: Unknown option “-rF”` on yay fish completions file

**Comment by Morganamilo** [comment]
In what version of yay?

**Comment by KokaKiwi** [comment]
`yay v9.4.2.r6.g662ce99 - libalpm v12.0.0`

**Comment by KokaKiwi** [comment]
I use yay with the AUR package `yay-git` (because i like living on the edge, arch user etc.)

**Comment by Morganamilo** [comment]
Looks like -F was added in git but is not in the current release... https://github.com/fish-shell/fish-shell/commit/4ebb6cf39eefbf4eedda7a12927c17fb1f2aef43

That's what happens when I don't test the PR.

**Comment by akiirui** [comment]
@KokaKiwi 
OMG... `-F` is new option of `complete` in `fish-shell 3.1.0` really.
And it's have not release. I forget it...
@Morganamilo 
Thanks for fix `-F` option.

**Pull request merged**
