### PR TITLE
print: out-of-date format

### PR DESCRIPTION
**Pull request by simon04**
Consistently use the same date format for all dates.

### CODE REVIEW

**Comment by Jguer** [comment]
Then isn't it inconsistent with the search result out of date `toprint += bold(red("(Out-of-date "+formatTime(res.OutOfDate)+")")) + " "`? 

Also removing the yes from it would make more sense if then the date is printed in red() imo

**Comment by simon04** [comment]
True. I guess at this place, one would want a concise (date only) output.

I find the inconsistency within the `-Si` output more distracting (and would happily accept the inconsistency between out-of-date outputs of very different commands):
```
$ yay -Si tippecanoe
...
First Submitted : Wed 17 May 2017 08:10:33 PM CEST
Last Modified   : Tue 16 Apr 2019 12:55:38 AM CEST
Out-of-date     : Yes [2019-05-30]
```

**Comment by Jguer** [comment]
It's well justified :wink:, I'm merging it

**Comment by Morganamilo** [comment]
Does this make format time an unused function?

**Comment by Jguer** [comment]
It's still used for search

**Pull request merged**
