### PR TITLE
Add experimental vote util to yay

### PR DESCRIPTION
**Pull request by Jguer**
Experimental support for aur package voting using [votar](https://github.com/Jguer/votar)

Partially implements https://github.com/Jguer/yay/issues/1075

- Requires `AUR_USERNAME` and `AUR_PASSWORD` to be set
- `yay -Wv <packages>` votes for packages
- `yay -Wu <packages>` removes votes from packages

### CODE REVIEW

**Comment by Morganamilo** [comment]
I think web login may be a bad idea. The aur already has an api for this `ssh aur.archlinux.org vote yay`

**Comment by Jguer** [comment]
> I think web login may be a bad idea. The aur already has an api for this `ssh aur.archlinux.org vote yay`

That's great to know, was not aware of it, will add support to the upstream library as default (web will always be flaky)

**Comment by Morganamilo** [comment]
There's a bunch you can do!

```
morganamilo@Octavia ~ %  ssh aur.archlinux.org help
Commands:
  adopt <name>                      Adopt a package base.
  disown <name>                     Disown a package base.
  flag <name> <comment>             Flag a package base out-of-date.
  git-receive-pack                  Internal command used with Git.
  git-upload-pack                   Internal command used with Git.
  help                              Show this help message and exit.
  list-repos                        List all your repositories.
  restore <name>                    Restore a deleted package base.
  set-comaintainers <name> [...]    Set package base co-maintainers.
  set-keywords <name> [...]         Change package base keywords.
  setup-repo <name>                 Create a repository (deprecated).
  unflag <name>                     Remove out-of-date flag from a package base.
  unvote <name>                     Remove vote from a package base.
  vote <name>                       Vote for a package base.
```

**Comment by Jguer** [comment]
TIL, `unflag` in particular might be useful :smile:

**Pull request merged**
